/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestSite - struct for BulkDeviceWithConfigContextRequestSite
type BulkDeviceWithConfigContextRequestSite struct {
	BriefSiteRequest *BriefSiteRequest
	Int32            *int32
}

// BriefSiteRequestAsBulkDeviceWithConfigContextRequestSite is a convenience function that returns BriefSiteRequest wrapped in BulkDeviceWithConfigContextRequestSite
func BriefSiteRequestAsBulkDeviceWithConfigContextRequestSite(v *BriefSiteRequest) BulkDeviceWithConfigContextRequestSite {
	return BulkDeviceWithConfigContextRequestSite{
		BriefSiteRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestSite is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestSite
func Int32AsBulkDeviceWithConfigContextRequestSite(v *int32) BulkDeviceWithConfigContextRequestSite {
	return BulkDeviceWithConfigContextRequestSite{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestSite) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefSiteRequest
	err = newStrictDecoder(data).Decode(&dst.BriefSiteRequest)
	if err == nil {
		jsonBriefSiteRequest, _ := json.Marshal(dst.BriefSiteRequest)
		if string(jsonBriefSiteRequest) == "{}" { // empty struct
			dst.BriefSiteRequest = nil
		} else {
			if err = validator.Validate(dst.BriefSiteRequest); err != nil {
				dst.BriefSiteRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefSiteRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefSiteRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestSite)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestSite): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestSite)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestSite): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestSite)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestSite) MarshalJSON() ([]byte, error) {
	if src.BriefSiteRequest != nil {
		return json.Marshal(&src.BriefSiteRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestSite) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefSiteRequest != nil {
		return obj.BriefSiteRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestSite) GetActualInstanceValue() interface{} {
	if obj.BriefSiteRequest != nil {
		return *obj.BriefSiteRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestSite struct {
	value *BulkDeviceWithConfigContextRequestSite
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestSite) Get() *BulkDeviceWithConfigContextRequestSite {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestSite) Set(val *BulkDeviceWithConfigContextRequestSite) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestSite) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestSite(val *BulkDeviceWithConfigContextRequestSite) *NullableBulkDeviceWithConfigContextRequestSite {
	return &NullableBulkDeviceWithConfigContextRequestSite{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
