/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceRoleRequestConfigTemplate - struct for BulkDeviceRoleRequestConfigTemplate
type BulkDeviceRoleRequestConfigTemplate struct {
	BriefConfigTemplateRequest *BriefConfigTemplateRequest
	Int32                      *int32
}

// BriefConfigTemplateRequestAsBulkDeviceRoleRequestConfigTemplate is a convenience function that returns BriefConfigTemplateRequest wrapped in BulkDeviceRoleRequestConfigTemplate
func BriefConfigTemplateRequestAsBulkDeviceRoleRequestConfigTemplate(v *BriefConfigTemplateRequest) BulkDeviceRoleRequestConfigTemplate {
	return BulkDeviceRoleRequestConfigTemplate{
		BriefConfigTemplateRequest: v,
	}
}

// int32AsBulkDeviceRoleRequestConfigTemplate is a convenience function that returns int32 wrapped in BulkDeviceRoleRequestConfigTemplate
func Int32AsBulkDeviceRoleRequestConfigTemplate(v *int32) BulkDeviceRoleRequestConfigTemplate {
	return BulkDeviceRoleRequestConfigTemplate{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceRoleRequestConfigTemplate) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefConfigTemplateRequest
	err = newStrictDecoder(data).Decode(&dst.BriefConfigTemplateRequest)
	if err == nil {
		jsonBriefConfigTemplateRequest, _ := json.Marshal(dst.BriefConfigTemplateRequest)
		if string(jsonBriefConfigTemplateRequest) == "{}" { // empty struct
			dst.BriefConfigTemplateRequest = nil
		} else {
			if err = validator.Validate(dst.BriefConfigTemplateRequest); err != nil {
				dst.BriefConfigTemplateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefConfigTemplateRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefConfigTemplateRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceRoleRequestConfigTemplate)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceRoleRequestConfigTemplate): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceRoleRequestConfigTemplate)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceRoleRequestConfigTemplate): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceRoleRequestConfigTemplate)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceRoleRequestConfigTemplate) MarshalJSON() ([]byte, error) {
	if src.BriefConfigTemplateRequest != nil {
		return json.Marshal(&src.BriefConfigTemplateRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceRoleRequestConfigTemplate) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefConfigTemplateRequest != nil {
		return obj.BriefConfigTemplateRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceRoleRequestConfigTemplate) GetActualInstanceValue() interface{} {
	if obj.BriefConfigTemplateRequest != nil {
		return *obj.BriefConfigTemplateRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceRoleRequestConfigTemplate struct {
	value *BulkDeviceRoleRequestConfigTemplate
	isSet bool
}

func (v NullableBulkDeviceRoleRequestConfigTemplate) Get() *BulkDeviceRoleRequestConfigTemplate {
	return v.value
}

func (v *NullableBulkDeviceRoleRequestConfigTemplate) Set(val *BulkDeviceRoleRequestConfigTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceRoleRequestConfigTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceRoleRequestConfigTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceRoleRequestConfigTemplate(val *BulkDeviceRoleRequestConfigTemplate) *NullableBulkDeviceRoleRequestConfigTemplate {
	return &NullableBulkDeviceRoleRequestConfigTemplate{value: val, isSet: true}
}

func (v NullableBulkDeviceRoleRequestConfigTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceRoleRequestConfigTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
