/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkDeviceWithConfigContextRequestAirflow * `front-to-rear` - Front to rear * `rear-to-front` - Rear to front * `left-to-right` - Left to right * `right-to-left` - Right to left * `side-to-rear` - Side to rear * `rear-to-side` - Rear to side * `bottom-to-top` - Bottom to top * `top-to-bottom` - Top to bottom * `passive` - Passive * `mixed` - Mixed
type BulkDeviceWithConfigContextRequestAirflow string

// List of BulkDeviceWithConfigContextRequest_airflow
const (
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_FRONT_TO_REAR BulkDeviceWithConfigContextRequestAirflow = "front-to-rear"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_REAR_TO_FRONT BulkDeviceWithConfigContextRequestAirflow = "rear-to-front"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_LEFT_TO_RIGHT BulkDeviceWithConfigContextRequestAirflow = "left-to-right"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_RIGHT_TO_LEFT BulkDeviceWithConfigContextRequestAirflow = "right-to-left"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_SIDE_TO_REAR  BulkDeviceWithConfigContextRequestAirflow = "side-to-rear"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_REAR_TO_SIDE  BulkDeviceWithConfigContextRequestAirflow = "rear-to-side"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_BOTTOM_TO_TOP BulkDeviceWithConfigContextRequestAirflow = "bottom-to-top"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_TOP_TO_BOTTOM BulkDeviceWithConfigContextRequestAirflow = "top-to-bottom"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_PASSIVE       BulkDeviceWithConfigContextRequestAirflow = "passive"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_MIXED         BulkDeviceWithConfigContextRequestAirflow = "mixed"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTAIRFLOW_EMPTY         BulkDeviceWithConfigContextRequestAirflow = ""
)

// All allowed values of BulkDeviceWithConfigContextRequestAirflow enum
var AllowedBulkDeviceWithConfigContextRequestAirflowEnumValues = []BulkDeviceWithConfigContextRequestAirflow{
	"front-to-rear",
	"rear-to-front",
	"left-to-right",
	"right-to-left",
	"side-to-rear",
	"rear-to-side",
	"bottom-to-top",
	"top-to-bottom",
	"passive",
	"mixed",
	"",
}

func (v *BulkDeviceWithConfigContextRequestAirflow) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkDeviceWithConfigContextRequestAirflow(value)
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestAirflowEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkDeviceWithConfigContextRequestAirflow", value)
}

// NewBulkDeviceWithConfigContextRequestAirflowFromValue returns a pointer to a valid BulkDeviceWithConfigContextRequestAirflow
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkDeviceWithConfigContextRequestAirflowFromValue(v string) (*BulkDeviceWithConfigContextRequestAirflow, error) {
	ev := BulkDeviceWithConfigContextRequestAirflow(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkDeviceWithConfigContextRequestAirflow: valid values are %v", v, AllowedBulkDeviceWithConfigContextRequestAirflowEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkDeviceWithConfigContextRequestAirflow) IsValid() bool {
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestAirflowEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkDeviceWithConfigContextRequest_airflow value
func (v BulkDeviceWithConfigContextRequestAirflow) Ptr() *BulkDeviceWithConfigContextRequestAirflow {
	return &v
}

type NullableBulkDeviceWithConfigContextRequestAirflow struct {
	value *BulkDeviceWithConfigContextRequestAirflow
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestAirflow) Get() *BulkDeviceWithConfigContextRequestAirflow {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestAirflow) Set(val *BulkDeviceWithConfigContextRequestAirflow) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestAirflow) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestAirflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestAirflow(val *BulkDeviceWithConfigContextRequestAirflow) *NullableBulkDeviceWithConfigContextRequestAirflow {
	return &NullableBulkDeviceWithConfigContextRequestAirflow{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestAirflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestAirflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
