/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkVirtualMachineWithConfigContextRequestStatus * `offline` - Offline * `active` - Active * `planned` - Planned * `staged` - Staged * `failed` - Failed * `decommissioning` - Decommissioning * `paused` - Paused
type BulkVirtualMachineWithConfigContextRequestStatus string

// List of BulkVirtualMachineWithConfigContextRequest_status
const (
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_OFFLINE         BulkVirtualMachineWithConfigContextRequestStatus = "offline"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_ACTIVE          BulkVirtualMachineWithConfigContextRequestStatus = "active"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_PLANNED         BulkVirtualMachineWithConfigContextRequestStatus = "planned"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_STAGED          BulkVirtualMachineWithConfigContextRequestStatus = "staged"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_FAILED          BulkVirtualMachineWithConfigContextRequestStatus = "failed"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_DECOMMISSIONING BulkVirtualMachineWithConfigContextRequestStatus = "decommissioning"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTATUS_PAUSED          BulkVirtualMachineWithConfigContextRequestStatus = "paused"
)

// All allowed values of BulkVirtualMachineWithConfigContextRequestStatus enum
var AllowedBulkVirtualMachineWithConfigContextRequestStatusEnumValues = []BulkVirtualMachineWithConfigContextRequestStatus{
	"offline",
	"active",
	"planned",
	"staged",
	"failed",
	"decommissioning",
	"paused",
}

func (v *BulkVirtualMachineWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkVirtualMachineWithConfigContextRequestStatus(value)
	for _, existing := range AllowedBulkVirtualMachineWithConfigContextRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkVirtualMachineWithConfigContextRequestStatus", value)
}

// NewBulkVirtualMachineWithConfigContextRequestStatusFromValue returns a pointer to a valid BulkVirtualMachineWithConfigContextRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkVirtualMachineWithConfigContextRequestStatusFromValue(v string) (*BulkVirtualMachineWithConfigContextRequestStatus, error) {
	ev := BulkVirtualMachineWithConfigContextRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkVirtualMachineWithConfigContextRequestStatus: valid values are %v", v, AllowedBulkVirtualMachineWithConfigContextRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkVirtualMachineWithConfigContextRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkVirtualMachineWithConfigContextRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkVirtualMachineWithConfigContextRequest_status value
func (v BulkVirtualMachineWithConfigContextRequestStatus) Ptr() *BulkVirtualMachineWithConfigContextRequestStatus {
	return &v
}

type NullableBulkVirtualMachineWithConfigContextRequestStatus struct {
	value *BulkVirtualMachineWithConfigContextRequestStatus
	isSet bool
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStatus) Get() *BulkVirtualMachineWithConfigContextRequestStatus {
	return v.value
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStatus) Set(val *BulkVirtualMachineWithConfigContextRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVirtualMachineWithConfigContextRequestStatus(val *BulkVirtualMachineWithConfigContextRequestStatus) *NullableBulkVirtualMachineWithConfigContextRequestStatus {
	return &NullableBulkVirtualMachineWithConfigContextRequestStatus{value: val, isSet: true}
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
