/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestPrimaryIp4 - struct for BulkDeviceWithConfigContextRequestPrimaryIp4
type BulkDeviceWithConfigContextRequestPrimaryIp4 struct {
	BriefIPAddressRequest *BriefIPAddressRequest
	Int32                 *int32
}

// BriefIPAddressRequestAsBulkDeviceWithConfigContextRequestPrimaryIp4 is a convenience function that returns BriefIPAddressRequest wrapped in BulkDeviceWithConfigContextRequestPrimaryIp4
func BriefIPAddressRequestAsBulkDeviceWithConfigContextRequestPrimaryIp4(v *BriefIPAddressRequest) BulkDeviceWithConfigContextRequestPrimaryIp4 {
	return BulkDeviceWithConfigContextRequestPrimaryIp4{
		BriefIPAddressRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestPrimaryIp4 is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestPrimaryIp4
func Int32AsBulkDeviceWithConfigContextRequestPrimaryIp4(v *int32) BulkDeviceWithConfigContextRequestPrimaryIp4 {
	return BulkDeviceWithConfigContextRequestPrimaryIp4{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestPrimaryIp4) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefIPAddressRequest
	err = newStrictDecoder(data).Decode(&dst.BriefIPAddressRequest)
	if err == nil {
		jsonBriefIPAddressRequest, _ := json.Marshal(dst.BriefIPAddressRequest)
		if string(jsonBriefIPAddressRequest) == "{}" { // empty struct
			dst.BriefIPAddressRequest = nil
		} else {
			if err = validator.Validate(dst.BriefIPAddressRequest); err != nil {
				dst.BriefIPAddressRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefIPAddressRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefIPAddressRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestPrimaryIp4)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestPrimaryIp4): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestPrimaryIp4)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestPrimaryIp4): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestPrimaryIp4)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestPrimaryIp4) MarshalJSON() ([]byte, error) {
	if src.BriefIPAddressRequest != nil {
		return json.Marshal(&src.BriefIPAddressRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestPrimaryIp4) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefIPAddressRequest != nil {
		return obj.BriefIPAddressRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestPrimaryIp4) GetActualInstanceValue() interface{} {
	if obj.BriefIPAddressRequest != nil {
		return *obj.BriefIPAddressRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestPrimaryIp4 struct {
	value *BulkDeviceWithConfigContextRequestPrimaryIp4
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestPrimaryIp4) Get() *BulkDeviceWithConfigContextRequestPrimaryIp4 {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestPrimaryIp4) Set(val *BulkDeviceWithConfigContextRequestPrimaryIp4) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestPrimaryIp4) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestPrimaryIp4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestPrimaryIp4(val *BulkDeviceWithConfigContextRequestPrimaryIp4) *NullableBulkDeviceWithConfigContextRequestPrimaryIp4 {
	return &NullableBulkDeviceWithConfigContextRequestPrimaryIp4{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestPrimaryIp4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestPrimaryIp4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
