/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkVLANTranslationRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkVLANTranslationRuleRequest{}

// PatchedBulkVLANTranslationRuleRequest Adds support for custom fields and tags.
type PatchedBulkVLANTranslationRuleRequest struct {
	Id     int32  `json:"id"`
	Policy *int32 `json:"policy,omitempty"`
	// Numeric VLAN ID (1-4094)
	LocalVid *int32 `json:"local_vid,omitempty"`
	// Numeric VLAN ID (1-4094)
	RemoteVid            *int32  `json:"remote_vid,omitempty"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkVLANTranslationRuleRequest PatchedBulkVLANTranslationRuleRequest

// NewPatchedBulkVLANTranslationRuleRequest instantiates a new PatchedBulkVLANTranslationRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkVLANTranslationRuleRequest(id int32) *PatchedBulkVLANTranslationRuleRequest {
	this := PatchedBulkVLANTranslationRuleRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkVLANTranslationRuleRequestWithDefaults instantiates a new PatchedBulkVLANTranslationRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkVLANTranslationRuleRequestWithDefaults() *PatchedBulkVLANTranslationRuleRequest {
	this := PatchedBulkVLANTranslationRuleRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkVLANTranslationRuleRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkVLANTranslationRuleRequest) SetId(v int32) {
	o.Id = v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *PatchedBulkVLANTranslationRuleRequest) GetPolicy() int32 {
	if o == nil || IsNil(o.Policy) {
		var ret int32
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) GetPolicyOk() (*int32, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given int32 and assigns it to the Policy field.
func (o *PatchedBulkVLANTranslationRuleRequest) SetPolicy(v int32) {
	o.Policy = &v
}

// GetLocalVid returns the LocalVid field value if set, zero value otherwise.
func (o *PatchedBulkVLANTranslationRuleRequest) GetLocalVid() int32 {
	if o == nil || IsNil(o.LocalVid) {
		var ret int32
		return ret
	}
	return *o.LocalVid
}

// GetLocalVidOk returns a tuple with the LocalVid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) GetLocalVidOk() (*int32, bool) {
	if o == nil || IsNil(o.LocalVid) {
		return nil, false
	}
	return o.LocalVid, true
}

// HasLocalVid returns a boolean if a field has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) HasLocalVid() bool {
	if o != nil && !IsNil(o.LocalVid) {
		return true
	}

	return false
}

// SetLocalVid gets a reference to the given int32 and assigns it to the LocalVid field.
func (o *PatchedBulkVLANTranslationRuleRequest) SetLocalVid(v int32) {
	o.LocalVid = &v
}

// GetRemoteVid returns the RemoteVid field value if set, zero value otherwise.
func (o *PatchedBulkVLANTranslationRuleRequest) GetRemoteVid() int32 {
	if o == nil || IsNil(o.RemoteVid) {
		var ret int32
		return ret
	}
	return *o.RemoteVid
}

// GetRemoteVidOk returns a tuple with the RemoteVid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) GetRemoteVidOk() (*int32, bool) {
	if o == nil || IsNil(o.RemoteVid) {
		return nil, false
	}
	return o.RemoteVid, true
}

// HasRemoteVid returns a boolean if a field has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) HasRemoteVid() bool {
	if o != nil && !IsNil(o.RemoteVid) {
		return true
	}

	return false
}

// SetRemoteVid gets a reference to the given int32 and assigns it to the RemoteVid field.
func (o *PatchedBulkVLANTranslationRuleRequest) SetRemoteVid(v int32) {
	o.RemoteVid = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedBulkVLANTranslationRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedBulkVLANTranslationRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedBulkVLANTranslationRuleRequest) SetDescription(v string) {
	o.Description = &v
}

func (o PatchedBulkVLANTranslationRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkVLANTranslationRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.LocalVid) {
		toSerialize["local_vid"] = o.LocalVid
	}
	if !IsNil(o.RemoteVid) {
		toSerialize["remote_vid"] = o.RemoteVid
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkVLANTranslationRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkVLANTranslationRuleRequest := _PatchedBulkVLANTranslationRuleRequest{}

	err = json.Unmarshal(data, &varPatchedBulkVLANTranslationRuleRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkVLANTranslationRuleRequest(varPatchedBulkVLANTranslationRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "policy")
		delete(additionalProperties, "local_vid")
		delete(additionalProperties, "remote_vid")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkVLANTranslationRuleRequest struct {
	value *PatchedBulkVLANTranslationRuleRequest
	isSet bool
}

func (v NullablePatchedBulkVLANTranslationRuleRequest) Get() *PatchedBulkVLANTranslationRuleRequest {
	return v.value
}

func (v *NullablePatchedBulkVLANTranslationRuleRequest) Set(val *PatchedBulkVLANTranslationRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkVLANTranslationRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkVLANTranslationRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkVLANTranslationRuleRequest(val *PatchedBulkVLANTranslationRuleRequest) *NullablePatchedBulkVLANTranslationRuleRequest {
	return &NullablePatchedBulkVLANTranslationRuleRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkVLANTranslationRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkVLANTranslationRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
