/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkOwnerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkOwnerRequest{}

// BulkOwnerRequest Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
type BulkOwnerRequest struct {
	Id                   int32                         `json:"id"`
	Name                 string                        `json:"name"`
	Group                NullableBulkOwnerRequestGroup `json:"group,omitempty"`
	Description          *string                       `json:"description,omitempty"`
	UserGroups           []int32                       `json:"user_groups,omitempty"`
	Users                []int32                       `json:"users,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkOwnerRequest BulkOwnerRequest

// NewBulkOwnerRequest instantiates a new BulkOwnerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkOwnerRequest(id int32, name string) *BulkOwnerRequest {
	this := BulkOwnerRequest{}
	this.Id = id
	this.Name = name
	return &this
}

// NewBulkOwnerRequestWithDefaults instantiates a new BulkOwnerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkOwnerRequestWithDefaults() *BulkOwnerRequest {
	this := BulkOwnerRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkOwnerRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkOwnerRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkOwnerRequest) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *BulkOwnerRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkOwnerRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkOwnerRequest) SetName(v string) {
	o.Name = v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkOwnerRequest) GetGroup() BulkOwnerRequestGroup {
	if o == nil || IsNil(o.Group.Get()) {
		var ret BulkOwnerRequestGroup
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkOwnerRequest) GetGroupOk() (*BulkOwnerRequestGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *BulkOwnerRequest) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableBulkOwnerRequestGroup and assigns it to the Group field.
func (o *BulkOwnerRequest) SetGroup(v BulkOwnerRequestGroup) {
	o.Group.Set(&v)
}

// SetGroupNil sets the value for Group to be an explicit nil
func (o *BulkOwnerRequest) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *BulkOwnerRequest) UnsetGroup() {
	o.Group.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BulkOwnerRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkOwnerRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BulkOwnerRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BulkOwnerRequest) SetDescription(v string) {
	o.Description = &v
}

// GetUserGroups returns the UserGroups field value if set, zero value otherwise.
func (o *BulkOwnerRequest) GetUserGroups() []int32 {
	if o == nil || IsNil(o.UserGroups) {
		var ret []int32
		return ret
	}
	return o.UserGroups
}

// GetUserGroupsOk returns a tuple with the UserGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkOwnerRequest) GetUserGroupsOk() ([]int32, bool) {
	if o == nil || IsNil(o.UserGroups) {
		return nil, false
	}
	return o.UserGroups, true
}

// HasUserGroups returns a boolean if a field has been set.
func (o *BulkOwnerRequest) HasUserGroups() bool {
	if o != nil && !IsNil(o.UserGroups) {
		return true
	}

	return false
}

// SetUserGroups gets a reference to the given []int32 and assigns it to the UserGroups field.
func (o *BulkOwnerRequest) SetUserGroups(v []int32) {
	o.UserGroups = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *BulkOwnerRequest) GetUsers() []int32 {
	if o == nil || IsNil(o.Users) {
		var ret []int32
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkOwnerRequest) GetUsersOk() ([]int32, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *BulkOwnerRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []int32 and assigns it to the Users field.
func (o *BulkOwnerRequest) SetUsers(v []int32) {
	o.Users = v
}

func (o BulkOwnerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkOwnerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.UserGroups) {
		toSerialize["user_groups"] = o.UserGroups
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkOwnerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBulkOwnerRequest := _BulkOwnerRequest{}

	err = json.Unmarshal(data, &varBulkOwnerRequest)

	if err != nil {
		return err
	}

	*o = BulkOwnerRequest(varBulkOwnerRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "group")
		delete(additionalProperties, "description")
		delete(additionalProperties, "user_groups")
		delete(additionalProperties, "users")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkOwnerRequest struct {
	value *BulkOwnerRequest
	isSet bool
}

func (v NullableBulkOwnerRequest) Get() *BulkOwnerRequest {
	return v.value
}

func (v *NullableBulkOwnerRequest) Set(val *BulkOwnerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkOwnerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkOwnerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkOwnerRequest(val *BulkOwnerRequest) *NullableBulkOwnerRequest {
	return &NullableBulkOwnerRequest{value: val, isSet: true}
}

func (v NullableBulkOwnerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkOwnerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
