/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkVirtualMachineWithConfigContextRequestRole - struct for BulkVirtualMachineWithConfigContextRequestRole
type BulkVirtualMachineWithConfigContextRequestRole struct {
	BriefDeviceRoleRequest *BriefDeviceRoleRequest
	Int32                  *int32
}

// BriefDeviceRoleRequestAsBulkVirtualMachineWithConfigContextRequestRole is a convenience function that returns BriefDeviceRoleRequest wrapped in BulkVirtualMachineWithConfigContextRequestRole
func BriefDeviceRoleRequestAsBulkVirtualMachineWithConfigContextRequestRole(v *BriefDeviceRoleRequest) BulkVirtualMachineWithConfigContextRequestRole {
	return BulkVirtualMachineWithConfigContextRequestRole{
		BriefDeviceRoleRequest: v,
	}
}

// int32AsBulkVirtualMachineWithConfigContextRequestRole is a convenience function that returns int32 wrapped in BulkVirtualMachineWithConfigContextRequestRole
func Int32AsBulkVirtualMachineWithConfigContextRequestRole(v *int32) BulkVirtualMachineWithConfigContextRequestRole {
	return BulkVirtualMachineWithConfigContextRequestRole{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkVirtualMachineWithConfigContextRequestRole) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefDeviceRoleRequest
	err = newStrictDecoder(data).Decode(&dst.BriefDeviceRoleRequest)
	if err == nil {
		jsonBriefDeviceRoleRequest, _ := json.Marshal(dst.BriefDeviceRoleRequest)
		if string(jsonBriefDeviceRoleRequest) == "{}" { // empty struct
			dst.BriefDeviceRoleRequest = nil
		} else {
			if err = validator.Validate(dst.BriefDeviceRoleRequest); err != nil {
				dst.BriefDeviceRoleRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefDeviceRoleRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefDeviceRoleRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkVirtualMachineWithConfigContextRequestRole)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestRole): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestRole)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestRole): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestRole)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkVirtualMachineWithConfigContextRequestRole) MarshalJSON() ([]byte, error) {
	if src.BriefDeviceRoleRequest != nil {
		return json.Marshal(&src.BriefDeviceRoleRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkVirtualMachineWithConfigContextRequestRole) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefDeviceRoleRequest != nil {
		return obj.BriefDeviceRoleRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkVirtualMachineWithConfigContextRequestRole) GetActualInstanceValue() interface{} {
	if obj.BriefDeviceRoleRequest != nil {
		return *obj.BriefDeviceRoleRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkVirtualMachineWithConfigContextRequestRole struct {
	value *BulkVirtualMachineWithConfigContextRequestRole
	isSet bool
}

func (v NullableBulkVirtualMachineWithConfigContextRequestRole) Get() *BulkVirtualMachineWithConfigContextRequestRole {
	return v.value
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestRole) Set(val *BulkVirtualMachineWithConfigContextRequestRole) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVirtualMachineWithConfigContextRequestRole) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVirtualMachineWithConfigContextRequestRole(val *BulkVirtualMachineWithConfigContextRequestRole) *NullableBulkVirtualMachineWithConfigContextRequestRole {
	return &NullableBulkVirtualMachineWithConfigContextRequestRole{value: val, isSet: true}
}

func (v NullableBulkVirtualMachineWithConfigContextRequestRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
