/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestCluster - struct for BulkDeviceWithConfigContextRequestCluster
type BulkDeviceWithConfigContextRequestCluster struct {
	BriefClusterRequest *BriefClusterRequest
	Int32               *int32
}

// BriefClusterRequestAsBulkDeviceWithConfigContextRequestCluster is a convenience function that returns BriefClusterRequest wrapped in BulkDeviceWithConfigContextRequestCluster
func BriefClusterRequestAsBulkDeviceWithConfigContextRequestCluster(v *BriefClusterRequest) BulkDeviceWithConfigContextRequestCluster {
	return BulkDeviceWithConfigContextRequestCluster{
		BriefClusterRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestCluster is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestCluster
func Int32AsBulkDeviceWithConfigContextRequestCluster(v *int32) BulkDeviceWithConfigContextRequestCluster {
	return BulkDeviceWithConfigContextRequestCluster{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestCluster) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefClusterRequest
	err = newStrictDecoder(data).Decode(&dst.BriefClusterRequest)
	if err == nil {
		jsonBriefClusterRequest, _ := json.Marshal(dst.BriefClusterRequest)
		if string(jsonBriefClusterRequest) == "{}" { // empty struct
			dst.BriefClusterRequest = nil
		} else {
			if err = validator.Validate(dst.BriefClusterRequest); err != nil {
				dst.BriefClusterRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefClusterRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefClusterRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestCluster)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestCluster): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestCluster)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestCluster): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestCluster)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestCluster) MarshalJSON() ([]byte, error) {
	if src.BriefClusterRequest != nil {
		return json.Marshal(&src.BriefClusterRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestCluster) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefClusterRequest != nil {
		return obj.BriefClusterRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestCluster) GetActualInstanceValue() interface{} {
	if obj.BriefClusterRequest != nil {
		return *obj.BriefClusterRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestCluster struct {
	value *BulkDeviceWithConfigContextRequestCluster
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestCluster) Get() *BulkDeviceWithConfigContextRequestCluster {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestCluster) Set(val *BulkDeviceWithConfigContextRequestCluster) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestCluster(val *BulkDeviceWithConfigContextRequestCluster) *NullableBulkDeviceWithConfigContextRequestCluster {
	return &NullableBulkDeviceWithConfigContextRequestCluster{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
