/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestLocation - struct for BulkDeviceWithConfigContextRequestLocation
type BulkDeviceWithConfigContextRequestLocation struct {
	BriefLocationRequest *BriefLocationRequest
	Int32                *int32
}

// BriefLocationRequestAsBulkDeviceWithConfigContextRequestLocation is a convenience function that returns BriefLocationRequest wrapped in BulkDeviceWithConfigContextRequestLocation
func BriefLocationRequestAsBulkDeviceWithConfigContextRequestLocation(v *BriefLocationRequest) BulkDeviceWithConfigContextRequestLocation {
	return BulkDeviceWithConfigContextRequestLocation{
		BriefLocationRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestLocation is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestLocation
func Int32AsBulkDeviceWithConfigContextRequestLocation(v *int32) BulkDeviceWithConfigContextRequestLocation {
	return BulkDeviceWithConfigContextRequestLocation{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestLocation) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefLocationRequest
	err = newStrictDecoder(data).Decode(&dst.BriefLocationRequest)
	if err == nil {
		jsonBriefLocationRequest, _ := json.Marshal(dst.BriefLocationRequest)
		if string(jsonBriefLocationRequest) == "{}" { // empty struct
			dst.BriefLocationRequest = nil
		} else {
			if err = validator.Validate(dst.BriefLocationRequest); err != nil {
				dst.BriefLocationRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefLocationRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefLocationRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestLocation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestLocation): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestLocation)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestLocation): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestLocation)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestLocation) MarshalJSON() ([]byte, error) {
	if src.BriefLocationRequest != nil {
		return json.Marshal(&src.BriefLocationRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestLocation) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefLocationRequest != nil {
		return obj.BriefLocationRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestLocation) GetActualInstanceValue() interface{} {
	if obj.BriefLocationRequest != nil {
		return *obj.BriefLocationRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestLocation struct {
	value *BulkDeviceWithConfigContextRequestLocation
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestLocation) Get() *BulkDeviceWithConfigContextRequestLocation {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestLocation) Set(val *BulkDeviceWithConfigContextRequestLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestLocation(val *BulkDeviceWithConfigContextRequestLocation) *NullableBulkDeviceWithConfigContextRequestLocation {
	return &NullableBulkDeviceWithConfigContextRequestLocation{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
