/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestRack - struct for BulkDeviceWithConfigContextRequestRack
type BulkDeviceWithConfigContextRequestRack struct {
	BriefRackRequest *BriefRackRequest
	Int32            *int32
}

// BriefRackRequestAsBulkDeviceWithConfigContextRequestRack is a convenience function that returns BriefRackRequest wrapped in BulkDeviceWithConfigContextRequestRack
func BriefRackRequestAsBulkDeviceWithConfigContextRequestRack(v *BriefRackRequest) BulkDeviceWithConfigContextRequestRack {
	return BulkDeviceWithConfigContextRequestRack{
		BriefRackRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestRack is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestRack
func Int32AsBulkDeviceWithConfigContextRequestRack(v *int32) BulkDeviceWithConfigContextRequestRack {
	return BulkDeviceWithConfigContextRequestRack{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestRack) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefRackRequest
	err = newStrictDecoder(data).Decode(&dst.BriefRackRequest)
	if err == nil {
		jsonBriefRackRequest, _ := json.Marshal(dst.BriefRackRequest)
		if string(jsonBriefRackRequest) == "{}" { // empty struct
			dst.BriefRackRequest = nil
		} else {
			if err = validator.Validate(dst.BriefRackRequest); err != nil {
				dst.BriefRackRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefRackRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefRackRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestRack)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRack): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRack)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRack): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRack)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestRack) MarshalJSON() ([]byte, error) {
	if src.BriefRackRequest != nil {
		return json.Marshal(&src.BriefRackRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestRack) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefRackRequest != nil {
		return obj.BriefRackRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestRack) GetActualInstanceValue() interface{} {
	if obj.BriefRackRequest != nil {
		return *obj.BriefRackRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestRack struct {
	value *BulkDeviceWithConfigContextRequestRack
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestRack) Get() *BulkDeviceWithConfigContextRequestRack {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestRack) Set(val *BulkDeviceWithConfigContextRequestRack) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestRack) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestRack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestRack(val *BulkDeviceWithConfigContextRequestRack) *NullableBulkDeviceWithConfigContextRequestRack {
	return &NullableBulkDeviceWithConfigContextRequestRack{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestRack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestRack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
