/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestRole - struct for BulkDeviceWithConfigContextRequestRole
type BulkDeviceWithConfigContextRequestRole struct {
	BriefDeviceRoleRequest *BriefDeviceRoleRequest
	Int32                  *int32
}

// BriefDeviceRoleRequestAsBulkDeviceWithConfigContextRequestRole is a convenience function that returns BriefDeviceRoleRequest wrapped in BulkDeviceWithConfigContextRequestRole
func BriefDeviceRoleRequestAsBulkDeviceWithConfigContextRequestRole(v *BriefDeviceRoleRequest) BulkDeviceWithConfigContextRequestRole {
	return BulkDeviceWithConfigContextRequestRole{
		BriefDeviceRoleRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestRole is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestRole
func Int32AsBulkDeviceWithConfigContextRequestRole(v *int32) BulkDeviceWithConfigContextRequestRole {
	return BulkDeviceWithConfigContextRequestRole{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestRole) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefDeviceRoleRequest
	err = newStrictDecoder(data).Decode(&dst.BriefDeviceRoleRequest)
	if err == nil {
		jsonBriefDeviceRoleRequest, _ := json.Marshal(dst.BriefDeviceRoleRequest)
		if string(jsonBriefDeviceRoleRequest) == "{}" { // empty struct
			dst.BriefDeviceRoleRequest = nil
		} else {
			if err = validator.Validate(dst.BriefDeviceRoleRequest); err != nil {
				dst.BriefDeviceRoleRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefDeviceRoleRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefDeviceRoleRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestRole)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRole): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRole)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRole): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestRole)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestRole) MarshalJSON() ([]byte, error) {
	if src.BriefDeviceRoleRequest != nil {
		return json.Marshal(&src.BriefDeviceRoleRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestRole) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefDeviceRoleRequest != nil {
		return obj.BriefDeviceRoleRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestRole) GetActualInstanceValue() interface{} {
	if obj.BriefDeviceRoleRequest != nil {
		return *obj.BriefDeviceRoleRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestRole struct {
	value *BulkDeviceWithConfigContextRequestRole
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestRole) Get() *BulkDeviceWithConfigContextRequestRole {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestRole) Set(val *BulkDeviceWithConfigContextRequestRole) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestRole) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestRole(val *BulkDeviceWithConfigContextRequestRole) *NullableBulkDeviceWithConfigContextRequestRole {
	return &NullableBulkDeviceWithConfigContextRequestRole{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
