/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkDeviceWithConfigContextRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDeviceWithConfigContextRequest{}

// BulkDeviceWithConfigContextRequest Base serializer class for models inheriting from PrimaryModel.
type BulkDeviceWithConfigContextRequest struct {
	Id         int32                                        `json:"id"`
	Name       NullableString                               `json:"name,omitempty"`
	DeviceType BulkDeviceBayTemplateRequestDeviceType       `json:"device_type"`
	Role       BulkDeviceWithConfigContextRequestRole       `json:"role"`
	Tenant     NullableASNRangeRequestTenant                `json:"tenant,omitempty"`
	Platform   NullableBulkDeviceTypeRequestDefaultPlatform `json:"platform,omitempty"`
	// Chassis serial number, assigned by the manufacturer
	Serial *string `json:"serial,omitempty"`
	// A unique tag used to identify this device
	AssetTag NullableString                                     `json:"asset_tag,omitempty"`
	Site     BulkDeviceWithConfigContextRequestSite             `json:"site"`
	Location NullableBulkDeviceWithConfigContextRequestLocation `json:"location,omitempty"`
	Rack     NullableBulkDeviceWithConfigContextRequestRack     `json:"rack,omitempty"`
	Position NullableFloat64                                    `json:"position,omitempty"`
	Face     *BulkDeviceWithConfigContextRequestFace            `json:"face,omitempty"`
	// GPS coordinate in decimal format (xx.yyyyyy)
	Latitude NullableFloat64 `json:"latitude,omitempty"`
	// GPS coordinate in decimal format (xx.yyyyyy)
	Longitude      NullableFloat64                                          `json:"longitude,omitempty"`
	Status         *BulkDeviceWithConfigContextRequestStatus                `json:"status,omitempty"`
	Airflow        *BulkDeviceWithConfigContextRequestAirflow               `json:"airflow,omitempty"`
	PrimaryIp4     NullableBulkDeviceWithConfigContextRequestPrimaryIp4     `json:"primary_ip4,omitempty"`
	PrimaryIp6     NullableBulkDeviceWithConfigContextRequestPrimaryIp4     `json:"primary_ip6,omitempty"`
	OobIp          NullableBulkDeviceWithConfigContextRequestPrimaryIp4     `json:"oob_ip,omitempty"`
	Cluster        NullableBulkDeviceWithConfigContextRequestCluster        `json:"cluster,omitempty"`
	VirtualChassis NullableBulkDeviceWithConfigContextRequestVirtualChassis `json:"virtual_chassis,omitempty"`
	VcPosition     NullableInt32                                            `json:"vc_position,omitempty"`
	// Virtual chassis master election priority
	VcPriority     NullableInt32                               `json:"vc_priority,omitempty"`
	Description    *string                                     `json:"description,omitempty"`
	Owner          NullableASNRangeRequestOwner                `json:"owner,omitempty"`
	Comments       *string                                     `json:"comments,omitempty"`
	ConfigTemplate NullableBulkDeviceRoleRequestConfigTemplate `json:"config_template,omitempty"`
	// Local config context data takes precedence over source contexts in the final rendered config context
	LocalContextData     interface{}            `json:"local_context_data,omitempty"`
	Tags                 []NestedTagRequest     `json:"tags,omitempty"`
	CustomFields         map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkDeviceWithConfigContextRequest BulkDeviceWithConfigContextRequest

// NewBulkDeviceWithConfigContextRequest instantiates a new BulkDeviceWithConfigContextRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDeviceWithConfigContextRequest(id int32, deviceType BulkDeviceBayTemplateRequestDeviceType, role BulkDeviceWithConfigContextRequestRole, site BulkDeviceWithConfigContextRequestSite) *BulkDeviceWithConfigContextRequest {
	this := BulkDeviceWithConfigContextRequest{}
	this.Id = id
	this.DeviceType = deviceType
	this.Role = role
	this.Site = site
	return &this
}

// NewBulkDeviceWithConfigContextRequestWithDefaults instantiates a new BulkDeviceWithConfigContextRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDeviceWithConfigContextRequestWithDefaults() *BulkDeviceWithConfigContextRequest {
	this := BulkDeviceWithConfigContextRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkDeviceWithConfigContextRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkDeviceWithConfigContextRequest) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *BulkDeviceWithConfigContextRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetName() {
	o.Name.Unset()
}

// GetDeviceType returns the DeviceType field value
func (o *BulkDeviceWithConfigContextRequest) GetDeviceType() BulkDeviceBayTemplateRequestDeviceType {
	if o == nil {
		var ret BulkDeviceBayTemplateRequestDeviceType
		return ret
	}

	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetDeviceTypeOk() (*BulkDeviceBayTemplateRequestDeviceType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceType, true
}

// SetDeviceType sets field value
func (o *BulkDeviceWithConfigContextRequest) SetDeviceType(v BulkDeviceBayTemplateRequestDeviceType) {
	o.DeviceType = v
}

// GetRole returns the Role field value
func (o *BulkDeviceWithConfigContextRequest) GetRole() BulkDeviceWithConfigContextRequestRole {
	if o == nil {
		var ret BulkDeviceWithConfigContextRequestRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetRoleOk() (*BulkDeviceWithConfigContextRequestRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *BulkDeviceWithConfigContextRequest) SetRole(v BulkDeviceWithConfigContextRequestRole) {
	o.Role = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetTenant() ASNRangeRequestTenant {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret ASNRangeRequestTenant
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetTenantOk() (*ASNRangeRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableASNRangeRequestTenant and assigns it to the Tenant field.
func (o *BulkDeviceWithConfigContextRequest) SetTenant(v ASNRangeRequestTenant) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetPlatform returns the Platform field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetPlatform() BulkDeviceTypeRequestDefaultPlatform {
	if o == nil || IsNil(o.Platform.Get()) {
		var ret BulkDeviceTypeRequestDefaultPlatform
		return ret
	}
	return *o.Platform.Get()
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetPlatformOk() (*BulkDeviceTypeRequestDefaultPlatform, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platform.Get(), o.Platform.IsSet()
}

// HasPlatform returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasPlatform() bool {
	if o != nil && o.Platform.IsSet() {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given NullableBulkDeviceTypeRequestDefaultPlatform and assigns it to the Platform field.
func (o *BulkDeviceWithConfigContextRequest) SetPlatform(v BulkDeviceTypeRequestDefaultPlatform) {
	o.Platform.Set(&v)
}

// SetPlatformNil sets the value for Platform to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetPlatformNil() {
	o.Platform.Set(nil)
}

// UnsetPlatform ensures that no value is present for Platform, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetPlatform() {
	o.Platform.Unset()
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *BulkDeviceWithConfigContextRequest) SetSerial(v string) {
	o.Serial = &v
}

// GetAssetTag returns the AssetTag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetAssetTag() string {
	if o == nil || IsNil(o.AssetTag.Get()) {
		var ret string
		return ret
	}
	return *o.AssetTag.Get()
}

// GetAssetTagOk returns a tuple with the AssetTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetAssetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetTag.Get(), o.AssetTag.IsSet()
}

// HasAssetTag returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasAssetTag() bool {
	if o != nil && o.AssetTag.IsSet() {
		return true
	}

	return false
}

// SetAssetTag gets a reference to the given NullableString and assigns it to the AssetTag field.
func (o *BulkDeviceWithConfigContextRequest) SetAssetTag(v string) {
	o.AssetTag.Set(&v)
}

// SetAssetTagNil sets the value for AssetTag to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetAssetTagNil() {
	o.AssetTag.Set(nil)
}

// UnsetAssetTag ensures that no value is present for AssetTag, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetAssetTag() {
	o.AssetTag.Unset()
}

// GetSite returns the Site field value
func (o *BulkDeviceWithConfigContextRequest) GetSite() BulkDeviceWithConfigContextRequestSite {
	if o == nil {
		var ret BulkDeviceWithConfigContextRequestSite
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetSiteOk() (*BulkDeviceWithConfigContextRequestSite, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *BulkDeviceWithConfigContextRequest) SetSite(v BulkDeviceWithConfigContextRequestSite) {
	o.Site = v
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetLocation() BulkDeviceWithConfigContextRequestLocation {
	if o == nil || IsNil(o.Location.Get()) {
		var ret BulkDeviceWithConfigContextRequestLocation
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetLocationOk() (*BulkDeviceWithConfigContextRequestLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableBulkDeviceWithConfigContextRequestLocation and assigns it to the Location field.
func (o *BulkDeviceWithConfigContextRequest) SetLocation(v BulkDeviceWithConfigContextRequestLocation) {
	o.Location.Set(&v)
}

// SetLocationNil sets the value for Location to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetLocation() {
	o.Location.Unset()
}

// GetRack returns the Rack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetRack() BulkDeviceWithConfigContextRequestRack {
	if o == nil || IsNil(o.Rack.Get()) {
		var ret BulkDeviceWithConfigContextRequestRack
		return ret
	}
	return *o.Rack.Get()
}

// GetRackOk returns a tuple with the Rack field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetRackOk() (*BulkDeviceWithConfigContextRequestRack, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rack.Get(), o.Rack.IsSet()
}

// HasRack returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasRack() bool {
	if o != nil && o.Rack.IsSet() {
		return true
	}

	return false
}

// SetRack gets a reference to the given NullableBulkDeviceWithConfigContextRequestRack and assigns it to the Rack field.
func (o *BulkDeviceWithConfigContextRequest) SetRack(v BulkDeviceWithConfigContextRequestRack) {
	o.Rack.Set(&v)
}

// SetRackNil sets the value for Rack to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetRackNil() {
	o.Rack.Set(nil)
}

// UnsetRack ensures that no value is present for Rack, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetRack() {
	o.Rack.Unset()
}

// GetPosition returns the Position field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetPosition() float64 {
	if o == nil || IsNil(o.Position.Get()) {
		var ret float64
		return ret
	}
	return *o.Position.Get()
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetPositionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Position.Get(), o.Position.IsSet()
}

// HasPosition returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasPosition() bool {
	if o != nil && o.Position.IsSet() {
		return true
	}

	return false
}

// SetPosition gets a reference to the given NullableFloat64 and assigns it to the Position field.
func (o *BulkDeviceWithConfigContextRequest) SetPosition(v float64) {
	o.Position.Set(&v)
}

// SetPositionNil sets the value for Position to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetPositionNil() {
	o.Position.Set(nil)
}

// UnsetPosition ensures that no value is present for Position, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetPosition() {
	o.Position.Unset()
}

// GetFace returns the Face field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetFace() BulkDeviceWithConfigContextRequestFace {
	if o == nil || IsNil(o.Face) {
		var ret BulkDeviceWithConfigContextRequestFace
		return ret
	}
	return *o.Face
}

// GetFaceOk returns a tuple with the Face field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetFaceOk() (*BulkDeviceWithConfigContextRequestFace, bool) {
	if o == nil || IsNil(o.Face) {
		return nil, false
	}
	return o.Face, true
}

// HasFace returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasFace() bool {
	if o != nil && !IsNil(o.Face) {
		return true
	}

	return false
}

// SetFace gets a reference to the given BulkDeviceWithConfigContextRequestFace and assigns it to the Face field.
func (o *BulkDeviceWithConfigContextRequest) SetFace(v BulkDeviceWithConfigContextRequestFace) {
	o.Face = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat64 and assigns it to the Latitude field.
func (o *BulkDeviceWithConfigContextRequest) SetLatitude(v float64) {
	o.Latitude.Set(&v)
}

// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat64 and assigns it to the Longitude field.
func (o *BulkDeviceWithConfigContextRequest) SetLongitude(v float64) {
	o.Longitude.Set(&v)
}

// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetStatus() BulkDeviceWithConfigContextRequestStatus {
	if o == nil || IsNil(o.Status) {
		var ret BulkDeviceWithConfigContextRequestStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetStatusOk() (*BulkDeviceWithConfigContextRequestStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given BulkDeviceWithConfigContextRequestStatus and assigns it to the Status field.
func (o *BulkDeviceWithConfigContextRequest) SetStatus(v BulkDeviceWithConfigContextRequestStatus) {
	o.Status = &v
}

// GetAirflow returns the Airflow field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetAirflow() BulkDeviceWithConfigContextRequestAirflow {
	if o == nil || IsNil(o.Airflow) {
		var ret BulkDeviceWithConfigContextRequestAirflow
		return ret
	}
	return *o.Airflow
}

// GetAirflowOk returns a tuple with the Airflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetAirflowOk() (*BulkDeviceWithConfigContextRequestAirflow, bool) {
	if o == nil || IsNil(o.Airflow) {
		return nil, false
	}
	return o.Airflow, true
}

// HasAirflow returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasAirflow() bool {
	if o != nil && !IsNil(o.Airflow) {
		return true
	}

	return false
}

// SetAirflow gets a reference to the given BulkDeviceWithConfigContextRequestAirflow and assigns it to the Airflow field.
func (o *BulkDeviceWithConfigContextRequest) SetAirflow(v BulkDeviceWithConfigContextRequestAirflow) {
	o.Airflow = &v
}

// GetPrimaryIp4 returns the PrimaryIp4 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetPrimaryIp4() BulkDeviceWithConfigContextRequestPrimaryIp4 {
	if o == nil || IsNil(o.PrimaryIp4.Get()) {
		var ret BulkDeviceWithConfigContextRequestPrimaryIp4
		return ret
	}
	return *o.PrimaryIp4.Get()
}

// GetPrimaryIp4Ok returns a tuple with the PrimaryIp4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetPrimaryIp4Ok() (*BulkDeviceWithConfigContextRequestPrimaryIp4, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp4.Get(), o.PrimaryIp4.IsSet()
}

// HasPrimaryIp4 returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasPrimaryIp4() bool {
	if o != nil && o.PrimaryIp4.IsSet() {
		return true
	}

	return false
}

// SetPrimaryIp4 gets a reference to the given NullableBulkDeviceWithConfigContextRequestPrimaryIp4 and assigns it to the PrimaryIp4 field.
func (o *BulkDeviceWithConfigContextRequest) SetPrimaryIp4(v BulkDeviceWithConfigContextRequestPrimaryIp4) {
	o.PrimaryIp4.Set(&v)
}

// SetPrimaryIp4Nil sets the value for PrimaryIp4 to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetPrimaryIp4Nil() {
	o.PrimaryIp4.Set(nil)
}

// UnsetPrimaryIp4 ensures that no value is present for PrimaryIp4, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetPrimaryIp4() {
	o.PrimaryIp4.Unset()
}

// GetPrimaryIp6 returns the PrimaryIp6 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetPrimaryIp6() BulkDeviceWithConfigContextRequestPrimaryIp4 {
	if o == nil || IsNil(o.PrimaryIp6.Get()) {
		var ret BulkDeviceWithConfigContextRequestPrimaryIp4
		return ret
	}
	return *o.PrimaryIp6.Get()
}

// GetPrimaryIp6Ok returns a tuple with the PrimaryIp6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetPrimaryIp6Ok() (*BulkDeviceWithConfigContextRequestPrimaryIp4, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp6.Get(), o.PrimaryIp6.IsSet()
}

// HasPrimaryIp6 returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasPrimaryIp6() bool {
	if o != nil && o.PrimaryIp6.IsSet() {
		return true
	}

	return false
}

// SetPrimaryIp6 gets a reference to the given NullableBulkDeviceWithConfigContextRequestPrimaryIp4 and assigns it to the PrimaryIp6 field.
func (o *BulkDeviceWithConfigContextRequest) SetPrimaryIp6(v BulkDeviceWithConfigContextRequestPrimaryIp4) {
	o.PrimaryIp6.Set(&v)
}

// SetPrimaryIp6Nil sets the value for PrimaryIp6 to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetPrimaryIp6Nil() {
	o.PrimaryIp6.Set(nil)
}

// UnsetPrimaryIp6 ensures that no value is present for PrimaryIp6, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetPrimaryIp6() {
	o.PrimaryIp6.Unset()
}

// GetOobIp returns the OobIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetOobIp() BulkDeviceWithConfigContextRequestPrimaryIp4 {
	if o == nil || IsNil(o.OobIp.Get()) {
		var ret BulkDeviceWithConfigContextRequestPrimaryIp4
		return ret
	}
	return *o.OobIp.Get()
}

// GetOobIpOk returns a tuple with the OobIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetOobIpOk() (*BulkDeviceWithConfigContextRequestPrimaryIp4, bool) {
	if o == nil {
		return nil, false
	}
	return o.OobIp.Get(), o.OobIp.IsSet()
}

// HasOobIp returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasOobIp() bool {
	if o != nil && o.OobIp.IsSet() {
		return true
	}

	return false
}

// SetOobIp gets a reference to the given NullableBulkDeviceWithConfigContextRequestPrimaryIp4 and assigns it to the OobIp field.
func (o *BulkDeviceWithConfigContextRequest) SetOobIp(v BulkDeviceWithConfigContextRequestPrimaryIp4) {
	o.OobIp.Set(&v)
}

// SetOobIpNil sets the value for OobIp to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetOobIpNil() {
	o.OobIp.Set(nil)
}

// UnsetOobIp ensures that no value is present for OobIp, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetOobIp() {
	o.OobIp.Unset()
}

// GetCluster returns the Cluster field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetCluster() BulkDeviceWithConfigContextRequestCluster {
	if o == nil || IsNil(o.Cluster.Get()) {
		var ret BulkDeviceWithConfigContextRequestCluster
		return ret
	}
	return *o.Cluster.Get()
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetClusterOk() (*BulkDeviceWithConfigContextRequestCluster, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cluster.Get(), o.Cluster.IsSet()
}

// HasCluster returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasCluster() bool {
	if o != nil && o.Cluster.IsSet() {
		return true
	}

	return false
}

// SetCluster gets a reference to the given NullableBulkDeviceWithConfigContextRequestCluster and assigns it to the Cluster field.
func (o *BulkDeviceWithConfigContextRequest) SetCluster(v BulkDeviceWithConfigContextRequestCluster) {
	o.Cluster.Set(&v)
}

// SetClusterNil sets the value for Cluster to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetClusterNil() {
	o.Cluster.Set(nil)
}

// UnsetCluster ensures that no value is present for Cluster, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetCluster() {
	o.Cluster.Unset()
}

// GetVirtualChassis returns the VirtualChassis field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetVirtualChassis() BulkDeviceWithConfigContextRequestVirtualChassis {
	if o == nil || IsNil(o.VirtualChassis.Get()) {
		var ret BulkDeviceWithConfigContextRequestVirtualChassis
		return ret
	}
	return *o.VirtualChassis.Get()
}

// GetVirtualChassisOk returns a tuple with the VirtualChassis field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetVirtualChassisOk() (*BulkDeviceWithConfigContextRequestVirtualChassis, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualChassis.Get(), o.VirtualChassis.IsSet()
}

// HasVirtualChassis returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasVirtualChassis() bool {
	if o != nil && o.VirtualChassis.IsSet() {
		return true
	}

	return false
}

// SetVirtualChassis gets a reference to the given NullableBulkDeviceWithConfigContextRequestVirtualChassis and assigns it to the VirtualChassis field.
func (o *BulkDeviceWithConfigContextRequest) SetVirtualChassis(v BulkDeviceWithConfigContextRequestVirtualChassis) {
	o.VirtualChassis.Set(&v)
}

// SetVirtualChassisNil sets the value for VirtualChassis to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetVirtualChassisNil() {
	o.VirtualChassis.Set(nil)
}

// UnsetVirtualChassis ensures that no value is present for VirtualChassis, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetVirtualChassis() {
	o.VirtualChassis.Unset()
}

// GetVcPosition returns the VcPosition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetVcPosition() int32 {
	if o == nil || IsNil(o.VcPosition.Get()) {
		var ret int32
		return ret
	}
	return *o.VcPosition.Get()
}

// GetVcPositionOk returns a tuple with the VcPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetVcPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VcPosition.Get(), o.VcPosition.IsSet()
}

// HasVcPosition returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasVcPosition() bool {
	if o != nil && o.VcPosition.IsSet() {
		return true
	}

	return false
}

// SetVcPosition gets a reference to the given NullableInt32 and assigns it to the VcPosition field.
func (o *BulkDeviceWithConfigContextRequest) SetVcPosition(v int32) {
	o.VcPosition.Set(&v)
}

// SetVcPositionNil sets the value for VcPosition to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetVcPositionNil() {
	o.VcPosition.Set(nil)
}

// UnsetVcPosition ensures that no value is present for VcPosition, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetVcPosition() {
	o.VcPosition.Unset()
}

// GetVcPriority returns the VcPriority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetVcPriority() int32 {
	if o == nil || IsNil(o.VcPriority.Get()) {
		var ret int32
		return ret
	}
	return *o.VcPriority.Get()
}

// GetVcPriorityOk returns a tuple with the VcPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetVcPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VcPriority.Get(), o.VcPriority.IsSet()
}

// HasVcPriority returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasVcPriority() bool {
	if o != nil && o.VcPriority.IsSet() {
		return true
	}

	return false
}

// SetVcPriority gets a reference to the given NullableInt32 and assigns it to the VcPriority field.
func (o *BulkDeviceWithConfigContextRequest) SetVcPriority(v int32) {
	o.VcPriority.Set(&v)
}

// SetVcPriorityNil sets the value for VcPriority to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetVcPriorityNil() {
	o.VcPriority.Set(nil)
}

// UnsetVcPriority ensures that no value is present for VcPriority, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetVcPriority() {
	o.VcPriority.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BulkDeviceWithConfigContextRequest) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *BulkDeviceWithConfigContextRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *BulkDeviceWithConfigContextRequest) SetComments(v string) {
	o.Comments = &v
}

// GetConfigTemplate returns the ConfigTemplate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetConfigTemplate() BulkDeviceRoleRequestConfigTemplate {
	if o == nil || IsNil(o.ConfigTemplate.Get()) {
		var ret BulkDeviceRoleRequestConfigTemplate
		return ret
	}
	return *o.ConfigTemplate.Get()
}

// GetConfigTemplateOk returns a tuple with the ConfigTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetConfigTemplateOk() (*BulkDeviceRoleRequestConfigTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigTemplate.Get(), o.ConfigTemplate.IsSet()
}

// HasConfigTemplate returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasConfigTemplate() bool {
	if o != nil && o.ConfigTemplate.IsSet() {
		return true
	}

	return false
}

// SetConfigTemplate gets a reference to the given NullableBulkDeviceRoleRequestConfigTemplate and assigns it to the ConfigTemplate field.
func (o *BulkDeviceWithConfigContextRequest) SetConfigTemplate(v BulkDeviceRoleRequestConfigTemplate) {
	o.ConfigTemplate.Set(&v)
}

// SetConfigTemplateNil sets the value for ConfigTemplate to be an explicit nil
func (o *BulkDeviceWithConfigContextRequest) SetConfigTemplateNil() {
	o.ConfigTemplate.Set(nil)
}

// UnsetConfigTemplate ensures that no value is present for ConfigTemplate, not even an explicit nil
func (o *BulkDeviceWithConfigContextRequest) UnsetConfigTemplate() {
	o.ConfigTemplate.Unset()
}

// GetLocalContextData returns the LocalContextData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkDeviceWithConfigContextRequest) GetLocalContextData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LocalContextData
}

// GetLocalContextDataOk returns a tuple with the LocalContextData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkDeviceWithConfigContextRequest) GetLocalContextDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LocalContextData) {
		return nil, false
	}
	return &o.LocalContextData, true
}

// HasLocalContextData returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasLocalContextData() bool {
	if o != nil && !IsNil(o.LocalContextData) {
		return true
	}

	return false
}

// SetLocalContextData gets a reference to the given interface{} and assigns it to the LocalContextData field.
func (o *BulkDeviceWithConfigContextRequest) SetLocalContextData(v interface{}) {
	o.LocalContextData = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *BulkDeviceWithConfigContextRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *BulkDeviceWithConfigContextRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeviceWithConfigContextRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *BulkDeviceWithConfigContextRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *BulkDeviceWithConfigContextRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o BulkDeviceWithConfigContextRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDeviceWithConfigContextRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["device_type"] = o.DeviceType
	toSerialize["role"] = o.Role
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if o.Platform.IsSet() {
		toSerialize["platform"] = o.Platform.Get()
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if o.AssetTag.IsSet() {
		toSerialize["asset_tag"] = o.AssetTag.Get()
	}
	toSerialize["site"] = o.Site
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	if o.Rack.IsSet() {
		toSerialize["rack"] = o.Rack.Get()
	}
	if o.Position.IsSet() {
		toSerialize["position"] = o.Position.Get()
	}
	if !IsNil(o.Face) {
		toSerialize["face"] = o.Face
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Airflow) {
		toSerialize["airflow"] = o.Airflow
	}
	if o.PrimaryIp4.IsSet() {
		toSerialize["primary_ip4"] = o.PrimaryIp4.Get()
	}
	if o.PrimaryIp6.IsSet() {
		toSerialize["primary_ip6"] = o.PrimaryIp6.Get()
	}
	if o.OobIp.IsSet() {
		toSerialize["oob_ip"] = o.OobIp.Get()
	}
	if o.Cluster.IsSet() {
		toSerialize["cluster"] = o.Cluster.Get()
	}
	if o.VirtualChassis.IsSet() {
		toSerialize["virtual_chassis"] = o.VirtualChassis.Get()
	}
	if o.VcPosition.IsSet() {
		toSerialize["vc_position"] = o.VcPosition.Get()
	}
	if o.VcPriority.IsSet() {
		toSerialize["vc_priority"] = o.VcPriority.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if o.ConfigTemplate.IsSet() {
		toSerialize["config_template"] = o.ConfigTemplate.Get()
	}
	if o.LocalContextData != nil {
		toSerialize["local_context_data"] = o.LocalContextData
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkDeviceWithConfigContextRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"device_type",
		"role",
		"site",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBulkDeviceWithConfigContextRequest := _BulkDeviceWithConfigContextRequest{}

	err = json.Unmarshal(data, &varBulkDeviceWithConfigContextRequest)

	if err != nil {
		return err
	}

	*o = BulkDeviceWithConfigContextRequest(varBulkDeviceWithConfigContextRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "role")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "asset_tag")
		delete(additionalProperties, "site")
		delete(additionalProperties, "location")
		delete(additionalProperties, "rack")
		delete(additionalProperties, "position")
		delete(additionalProperties, "face")
		delete(additionalProperties, "latitude")
		delete(additionalProperties, "longitude")
		delete(additionalProperties, "status")
		delete(additionalProperties, "airflow")
		delete(additionalProperties, "primary_ip4")
		delete(additionalProperties, "primary_ip6")
		delete(additionalProperties, "oob_ip")
		delete(additionalProperties, "cluster")
		delete(additionalProperties, "virtual_chassis")
		delete(additionalProperties, "vc_position")
		delete(additionalProperties, "vc_priority")
		delete(additionalProperties, "description")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "config_template")
		delete(additionalProperties, "local_context_data")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkDeviceWithConfigContextRequest struct {
	value *BulkDeviceWithConfigContextRequest
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequest) Get() *BulkDeviceWithConfigContextRequest {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequest) Set(val *BulkDeviceWithConfigContextRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequest(val *BulkDeviceWithConfigContextRequest) *NullableBulkDeviceWithConfigContextRequest {
	return &NullableBulkDeviceWithConfigContextRequest{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
