/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkDeviceWithConfigContextRequestFace * `front` - Front * `rear` - Rear
type BulkDeviceWithConfigContextRequestFace string

// List of BulkDeviceWithConfigContextRequest_face
const (
	BULKDEVICEWITHCONFIGCONTEXTREQUESTFACE_FRONT BulkDeviceWithConfigContextRequestFace = "front"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTFACE_REAR  BulkDeviceWithConfigContextRequestFace = "rear"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTFACE_EMPTY BulkDeviceWithConfigContextRequestFace = ""
)

// All allowed values of BulkDeviceWithConfigContextRequestFace enum
var AllowedBulkDeviceWithConfigContextRequestFaceEnumValues = []BulkDeviceWithConfigContextRequestFace{
	"front",
	"rear",
	"",
}

func (v *BulkDeviceWithConfigContextRequestFace) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkDeviceWithConfigContextRequestFace(value)
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestFaceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkDeviceWithConfigContextRequestFace", value)
}

// NewBulkDeviceWithConfigContextRequestFaceFromValue returns a pointer to a valid BulkDeviceWithConfigContextRequestFace
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkDeviceWithConfigContextRequestFaceFromValue(v string) (*BulkDeviceWithConfigContextRequestFace, error) {
	ev := BulkDeviceWithConfigContextRequestFace(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkDeviceWithConfigContextRequestFace: valid values are %v", v, AllowedBulkDeviceWithConfigContextRequestFaceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkDeviceWithConfigContextRequestFace) IsValid() bool {
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestFaceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkDeviceWithConfigContextRequest_face value
func (v BulkDeviceWithConfigContextRequestFace) Ptr() *BulkDeviceWithConfigContextRequestFace {
	return &v
}

type NullableBulkDeviceWithConfigContextRequestFace struct {
	value *BulkDeviceWithConfigContextRequestFace
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestFace) Get() *BulkDeviceWithConfigContextRequestFace {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestFace) Set(val *BulkDeviceWithConfigContextRequestFace) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestFace) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestFace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestFace(val *BulkDeviceWithConfigContextRequestFace) *NullableBulkDeviceWithConfigContextRequestFace {
	return &NullableBulkDeviceWithConfigContextRequestFace{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestFace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestFace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
