/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkVirtualMachineWithConfigContextRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkVirtualMachineWithConfigContextRequest{}

// PatchedBulkVirtualMachineWithConfigContextRequest Base serializer class for models inheriting from PrimaryModel.
type PatchedBulkVirtualMachineWithConfigContextRequest struct {
	Id                 int32                                                                `json:"id"`
	Name               *string                                                              `json:"name,omitempty"`
	VirtualMachineType NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType `json:"virtual_machine_type,omitempty"`
	Role               NullableBulkVirtualMachineWithConfigContextRequestRole               `json:"role,omitempty"`
	Status             *BulkVirtualMachineWithConfigContextRequestStatus                    `json:"status,omitempty"`
	StartOnBoot        *BulkVirtualMachineWithConfigContextRequestStartOnBoot               `json:"start_on_boot,omitempty"`
	Site               NullableBulkVLANRequestSite                                          `json:"site,omitempty"`
	Cluster            NullableBulkDeviceWithConfigContextRequestCluster                    `json:"cluster,omitempty"`
	Device             NullableBulkDeviceBayRequestInstalledDevice                          `json:"device,omitempty"`
	Platform           NullableBulkDeviceTypeRequestDefaultPlatform                         `json:"platform,omitempty"`
	PrimaryIp4         NullableBulkDeviceWithConfigContextRequestPrimaryIp4                 `json:"primary_ip4,omitempty"`
	PrimaryIp6         NullableBulkDeviceWithConfigContextRequestPrimaryIp4                 `json:"primary_ip6,omitempty"`
	Vcpus              NullableFloat64                                                      `json:"vcpus,omitempty"`
	Memory             NullableInt32                                                        `json:"memory,omitempty"`
	Disk               NullableInt32                                                        `json:"disk,omitempty"`
	Description        *string                                                              `json:"description,omitempty"`
	Serial             *string                                                              `json:"serial,omitempty"`
	Tenant             NullableASNRangeRequestTenant                                        `json:"tenant,omitempty"`
	Owner              NullableASNRangeRequestOwner                                         `json:"owner,omitempty"`
	Comments           *string                                                              `json:"comments,omitempty"`
	Tags               []NestedTagRequest                                                   `json:"tags,omitempty"`
	// Local config context data takes precedence over source contexts in the final rendered config context
	LocalContextData     interface{}                                 `json:"local_context_data,omitempty"`
	ConfigTemplate       NullableBulkDeviceRoleRequestConfigTemplate `json:"config_template,omitempty"`
	CustomFields         map[string]interface{}                      `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkVirtualMachineWithConfigContextRequest PatchedBulkVirtualMachineWithConfigContextRequest

// NewPatchedBulkVirtualMachineWithConfigContextRequest instantiates a new PatchedBulkVirtualMachineWithConfigContextRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkVirtualMachineWithConfigContextRequest(id int32) *PatchedBulkVirtualMachineWithConfigContextRequest {
	this := PatchedBulkVirtualMachineWithConfigContextRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkVirtualMachineWithConfigContextRequestWithDefaults instantiates a new PatchedBulkVirtualMachineWithConfigContextRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkVirtualMachineWithConfigContextRequestWithDefaults() *PatchedBulkVirtualMachineWithConfigContextRequest {
	this := PatchedBulkVirtualMachineWithConfigContextRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetName(v string) {
	o.Name = &v
}

// GetVirtualMachineType returns the VirtualMachineType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetVirtualMachineType() BulkVirtualMachineWithConfigContextRequestVirtualMachineType {
	if o == nil || IsNil(o.VirtualMachineType.Get()) {
		var ret BulkVirtualMachineWithConfigContextRequestVirtualMachineType
		return ret
	}
	return *o.VirtualMachineType.Get()
}

// GetVirtualMachineTypeOk returns a tuple with the VirtualMachineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetVirtualMachineTypeOk() (*BulkVirtualMachineWithConfigContextRequestVirtualMachineType, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualMachineType.Get(), o.VirtualMachineType.IsSet()
}

// HasVirtualMachineType returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasVirtualMachineType() bool {
	if o != nil && o.VirtualMachineType.IsSet() {
		return true
	}

	return false
}

// SetVirtualMachineType gets a reference to the given NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType and assigns it to the VirtualMachineType field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetVirtualMachineType(v BulkVirtualMachineWithConfigContextRequestVirtualMachineType) {
	o.VirtualMachineType.Set(&v)
}

// SetVirtualMachineTypeNil sets the value for VirtualMachineType to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetVirtualMachineTypeNil() {
	o.VirtualMachineType.Set(nil)
}

// UnsetVirtualMachineType ensures that no value is present for VirtualMachineType, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetVirtualMachineType() {
	o.VirtualMachineType.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetRole() BulkVirtualMachineWithConfigContextRequestRole {
	if o == nil || IsNil(o.Role.Get()) {
		var ret BulkVirtualMachineWithConfigContextRequestRole
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetRoleOk() (*BulkVirtualMachineWithConfigContextRequestRole, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableBulkVirtualMachineWithConfigContextRequestRole and assigns it to the Role field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetRole(v BulkVirtualMachineWithConfigContextRequestRole) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetRole() {
	o.Role.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetStatus() BulkVirtualMachineWithConfigContextRequestStatus {
	if o == nil || IsNil(o.Status) {
		var ret BulkVirtualMachineWithConfigContextRequestStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetStatusOk() (*BulkVirtualMachineWithConfigContextRequestStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given BulkVirtualMachineWithConfigContextRequestStatus and assigns it to the Status field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetStatus(v BulkVirtualMachineWithConfigContextRequestStatus) {
	o.Status = &v
}

// GetStartOnBoot returns the StartOnBoot field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetStartOnBoot() BulkVirtualMachineWithConfigContextRequestStartOnBoot {
	if o == nil || IsNil(o.StartOnBoot) {
		var ret BulkVirtualMachineWithConfigContextRequestStartOnBoot
		return ret
	}
	return *o.StartOnBoot
}

// GetStartOnBootOk returns a tuple with the StartOnBoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetStartOnBootOk() (*BulkVirtualMachineWithConfigContextRequestStartOnBoot, bool) {
	if o == nil || IsNil(o.StartOnBoot) {
		return nil, false
	}
	return o.StartOnBoot, true
}

// HasStartOnBoot returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasStartOnBoot() bool {
	if o != nil && !IsNil(o.StartOnBoot) {
		return true
	}

	return false
}

// SetStartOnBoot gets a reference to the given BulkVirtualMachineWithConfigContextRequestStartOnBoot and assigns it to the StartOnBoot field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetStartOnBoot(v BulkVirtualMachineWithConfigContextRequestStartOnBoot) {
	o.StartOnBoot = &v
}

// GetSite returns the Site field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetSite() BulkVLANRequestSite {
	if o == nil || IsNil(o.Site.Get()) {
		var ret BulkVLANRequestSite
		return ret
	}
	return *o.Site.Get()
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetSiteOk() (*BulkVLANRequestSite, bool) {
	if o == nil {
		return nil, false
	}
	return o.Site.Get(), o.Site.IsSet()
}

// HasSite returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasSite() bool {
	if o != nil && o.Site.IsSet() {
		return true
	}

	return false
}

// SetSite gets a reference to the given NullableBulkVLANRequestSite and assigns it to the Site field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetSite(v BulkVLANRequestSite) {
	o.Site.Set(&v)
}

// SetSiteNil sets the value for Site to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetSiteNil() {
	o.Site.Set(nil)
}

// UnsetSite ensures that no value is present for Site, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetSite() {
	o.Site.Unset()
}

// GetCluster returns the Cluster field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetCluster() BulkDeviceWithConfigContextRequestCluster {
	if o == nil || IsNil(o.Cluster.Get()) {
		var ret BulkDeviceWithConfigContextRequestCluster
		return ret
	}
	return *o.Cluster.Get()
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetClusterOk() (*BulkDeviceWithConfigContextRequestCluster, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cluster.Get(), o.Cluster.IsSet()
}

// HasCluster returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasCluster() bool {
	if o != nil && o.Cluster.IsSet() {
		return true
	}

	return false
}

// SetCluster gets a reference to the given NullableBulkDeviceWithConfigContextRequestCluster and assigns it to the Cluster field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetCluster(v BulkDeviceWithConfigContextRequestCluster) {
	o.Cluster.Set(&v)
}

// SetClusterNil sets the value for Cluster to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetClusterNil() {
	o.Cluster.Set(nil)
}

// UnsetCluster ensures that no value is present for Cluster, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetCluster() {
	o.Cluster.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDevice() BulkDeviceBayRequestInstalledDevice {
	if o == nil || IsNil(o.Device.Get()) {
		var ret BulkDeviceBayRequestInstalledDevice
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDeviceOk() (*BulkDeviceBayRequestInstalledDevice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableBulkDeviceBayRequestInstalledDevice and assigns it to the Device field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetDevice(v BulkDeviceBayRequestInstalledDevice) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetDevice() {
	o.Device.Unset()
}

// GetPlatform returns the Platform field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPlatform() BulkDeviceTypeRequestDefaultPlatform {
	if o == nil || IsNil(o.Platform.Get()) {
		var ret BulkDeviceTypeRequestDefaultPlatform
		return ret
	}
	return *o.Platform.Get()
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPlatformOk() (*BulkDeviceTypeRequestDefaultPlatform, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platform.Get(), o.Platform.IsSet()
}

// HasPlatform returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasPlatform() bool {
	if o != nil && o.Platform.IsSet() {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given NullableBulkDeviceTypeRequestDefaultPlatform and assigns it to the Platform field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPlatform(v BulkDeviceTypeRequestDefaultPlatform) {
	o.Platform.Set(&v)
}

// SetPlatformNil sets the value for Platform to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPlatformNil() {
	o.Platform.Set(nil)
}

// UnsetPlatform ensures that no value is present for Platform, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetPlatform() {
	o.Platform.Unset()
}

// GetPrimaryIp4 returns the PrimaryIp4 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPrimaryIp4() BulkDeviceWithConfigContextRequestPrimaryIp4 {
	if o == nil || IsNil(o.PrimaryIp4.Get()) {
		var ret BulkDeviceWithConfigContextRequestPrimaryIp4
		return ret
	}
	return *o.PrimaryIp4.Get()
}

// GetPrimaryIp4Ok returns a tuple with the PrimaryIp4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPrimaryIp4Ok() (*BulkDeviceWithConfigContextRequestPrimaryIp4, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp4.Get(), o.PrimaryIp4.IsSet()
}

// HasPrimaryIp4 returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasPrimaryIp4() bool {
	if o != nil && o.PrimaryIp4.IsSet() {
		return true
	}

	return false
}

// SetPrimaryIp4 gets a reference to the given NullableBulkDeviceWithConfigContextRequestPrimaryIp4 and assigns it to the PrimaryIp4 field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPrimaryIp4(v BulkDeviceWithConfigContextRequestPrimaryIp4) {
	o.PrimaryIp4.Set(&v)
}

// SetPrimaryIp4Nil sets the value for PrimaryIp4 to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPrimaryIp4Nil() {
	o.PrimaryIp4.Set(nil)
}

// UnsetPrimaryIp4 ensures that no value is present for PrimaryIp4, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetPrimaryIp4() {
	o.PrimaryIp4.Unset()
}

// GetPrimaryIp6 returns the PrimaryIp6 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPrimaryIp6() BulkDeviceWithConfigContextRequestPrimaryIp4 {
	if o == nil || IsNil(o.PrimaryIp6.Get()) {
		var ret BulkDeviceWithConfigContextRequestPrimaryIp4
		return ret
	}
	return *o.PrimaryIp6.Get()
}

// GetPrimaryIp6Ok returns a tuple with the PrimaryIp6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetPrimaryIp6Ok() (*BulkDeviceWithConfigContextRequestPrimaryIp4, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp6.Get(), o.PrimaryIp6.IsSet()
}

// HasPrimaryIp6 returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasPrimaryIp6() bool {
	if o != nil && o.PrimaryIp6.IsSet() {
		return true
	}

	return false
}

// SetPrimaryIp6 gets a reference to the given NullableBulkDeviceWithConfigContextRequestPrimaryIp4 and assigns it to the PrimaryIp6 field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPrimaryIp6(v BulkDeviceWithConfigContextRequestPrimaryIp4) {
	o.PrimaryIp6.Set(&v)
}

// SetPrimaryIp6Nil sets the value for PrimaryIp6 to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetPrimaryIp6Nil() {
	o.PrimaryIp6.Set(nil)
}

// UnsetPrimaryIp6 ensures that no value is present for PrimaryIp6, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetPrimaryIp6() {
	o.PrimaryIp6.Unset()
}

// GetVcpus returns the Vcpus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetVcpus() float64 {
	if o == nil || IsNil(o.Vcpus.Get()) {
		var ret float64
		return ret
	}
	return *o.Vcpus.Get()
}

// GetVcpusOk returns a tuple with the Vcpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetVcpusOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vcpus.Get(), o.Vcpus.IsSet()
}

// HasVcpus returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasVcpus() bool {
	if o != nil && o.Vcpus.IsSet() {
		return true
	}

	return false
}

// SetVcpus gets a reference to the given NullableFloat64 and assigns it to the Vcpus field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetVcpus(v float64) {
	o.Vcpus.Set(&v)
}

// SetVcpusNil sets the value for Vcpus to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetVcpusNil() {
	o.Vcpus.Set(nil)
}

// UnsetVcpus ensures that no value is present for Vcpus, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetVcpus() {
	o.Vcpus.Unset()
}

// GetMemory returns the Memory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetMemory() int32 {
	if o == nil || IsNil(o.Memory.Get()) {
		var ret int32
		return ret
	}
	return *o.Memory.Get()
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetMemoryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Memory.Get(), o.Memory.IsSet()
}

// HasMemory returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasMemory() bool {
	if o != nil && o.Memory.IsSet() {
		return true
	}

	return false
}

// SetMemory gets a reference to the given NullableInt32 and assigns it to the Memory field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetMemory(v int32) {
	o.Memory.Set(&v)
}

// SetMemoryNil sets the value for Memory to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetMemoryNil() {
	o.Memory.Set(nil)
}

// UnsetMemory ensures that no value is present for Memory, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetMemory() {
	o.Memory.Unset()
}

// GetDisk returns the Disk field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDisk() int32 {
	if o == nil || IsNil(o.Disk.Get()) {
		var ret int32
		return ret
	}
	return *o.Disk.Get()
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDiskOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disk.Get(), o.Disk.IsSet()
}

// HasDisk returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasDisk() bool {
	if o != nil && o.Disk.IsSet() {
		return true
	}

	return false
}

// SetDisk gets a reference to the given NullableInt32 and assigns it to the Disk field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetDisk(v int32) {
	o.Disk.Set(&v)
}

// SetDiskNil sets the value for Disk to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetDiskNil() {
	o.Disk.Set(nil)
}

// UnsetDisk ensures that no value is present for Disk, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetDisk() {
	o.Disk.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetSerial(v string) {
	o.Serial = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetTenant() ASNRangeRequestTenant {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret ASNRangeRequestTenant
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetTenantOk() (*ASNRangeRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableASNRangeRequestTenant and assigns it to the Tenant field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetTenant(v ASNRangeRequestTenant) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetLocalContextData returns the LocalContextData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetLocalContextData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LocalContextData
}

// GetLocalContextDataOk returns a tuple with the LocalContextData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetLocalContextDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LocalContextData) {
		return nil, false
	}
	return &o.LocalContextData, true
}

// HasLocalContextData returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasLocalContextData() bool {
	if o != nil && !IsNil(o.LocalContextData) {
		return true
	}

	return false
}

// SetLocalContextData gets a reference to the given interface{} and assigns it to the LocalContextData field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetLocalContextData(v interface{}) {
	o.LocalContextData = v
}

// GetConfigTemplate returns the ConfigTemplate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetConfigTemplate() BulkDeviceRoleRequestConfigTemplate {
	if o == nil || IsNil(o.ConfigTemplate.Get()) {
		var ret BulkDeviceRoleRequestConfigTemplate
		return ret
	}
	return *o.ConfigTemplate.Get()
}

// GetConfigTemplateOk returns a tuple with the ConfigTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetConfigTemplateOk() (*BulkDeviceRoleRequestConfigTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigTemplate.Get(), o.ConfigTemplate.IsSet()
}

// HasConfigTemplate returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasConfigTemplate() bool {
	if o != nil && o.ConfigTemplate.IsSet() {
		return true
	}

	return false
}

// SetConfigTemplate gets a reference to the given NullableBulkDeviceRoleRequestConfigTemplate and assigns it to the ConfigTemplate field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetConfigTemplate(v BulkDeviceRoleRequestConfigTemplate) {
	o.ConfigTemplate.Set(&v)
}

// SetConfigTemplateNil sets the value for ConfigTemplate to be an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetConfigTemplateNil() {
	o.ConfigTemplate.Set(nil)
}

// UnsetConfigTemplate ensures that no value is present for ConfigTemplate, not even an explicit nil
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnsetConfigTemplate() {
	o.ConfigTemplate.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedBulkVirtualMachineWithConfigContextRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o PatchedBulkVirtualMachineWithConfigContextRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkVirtualMachineWithConfigContextRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.VirtualMachineType.IsSet() {
		toSerialize["virtual_machine_type"] = o.VirtualMachineType.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StartOnBoot) {
		toSerialize["start_on_boot"] = o.StartOnBoot
	}
	if o.Site.IsSet() {
		toSerialize["site"] = o.Site.Get()
	}
	if o.Cluster.IsSet() {
		toSerialize["cluster"] = o.Cluster.Get()
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if o.Platform.IsSet() {
		toSerialize["platform"] = o.Platform.Get()
	}
	if o.PrimaryIp4.IsSet() {
		toSerialize["primary_ip4"] = o.PrimaryIp4.Get()
	}
	if o.PrimaryIp6.IsSet() {
		toSerialize["primary_ip6"] = o.PrimaryIp6.Get()
	}
	if o.Vcpus.IsSet() {
		toSerialize["vcpus"] = o.Vcpus.Get()
	}
	if o.Memory.IsSet() {
		toSerialize["memory"] = o.Memory.Get()
	}
	if o.Disk.IsSet() {
		toSerialize["disk"] = o.Disk.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.LocalContextData != nil {
		toSerialize["local_context_data"] = o.LocalContextData
	}
	if o.ConfigTemplate.IsSet() {
		toSerialize["config_template"] = o.ConfigTemplate.Get()
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkVirtualMachineWithConfigContextRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkVirtualMachineWithConfigContextRequest := _PatchedBulkVirtualMachineWithConfigContextRequest{}

	err = json.Unmarshal(data, &varPatchedBulkVirtualMachineWithConfigContextRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkVirtualMachineWithConfigContextRequest(varPatchedBulkVirtualMachineWithConfigContextRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "virtual_machine_type")
		delete(additionalProperties, "role")
		delete(additionalProperties, "status")
		delete(additionalProperties, "start_on_boot")
		delete(additionalProperties, "site")
		delete(additionalProperties, "cluster")
		delete(additionalProperties, "device")
		delete(additionalProperties, "platform")
		delete(additionalProperties, "primary_ip4")
		delete(additionalProperties, "primary_ip6")
		delete(additionalProperties, "vcpus")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "disk")
		delete(additionalProperties, "description")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "local_context_data")
		delete(additionalProperties, "config_template")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkVirtualMachineWithConfigContextRequest struct {
	value *PatchedBulkVirtualMachineWithConfigContextRequest
	isSet bool
}

func (v NullablePatchedBulkVirtualMachineWithConfigContextRequest) Get() *PatchedBulkVirtualMachineWithConfigContextRequest {
	return v.value
}

func (v *NullablePatchedBulkVirtualMachineWithConfigContextRequest) Set(val *PatchedBulkVirtualMachineWithConfigContextRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkVirtualMachineWithConfigContextRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkVirtualMachineWithConfigContextRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkVirtualMachineWithConfigContextRequest(val *PatchedBulkVirtualMachineWithConfigContextRequest) *NullablePatchedBulkVirtualMachineWithConfigContextRequest {
	return &NullablePatchedBulkVirtualMachineWithConfigContextRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkVirtualMachineWithConfigContextRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkVirtualMachineWithConfigContextRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
