/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkDeviceWithConfigContextRequestStatus * `offline` - Offline * `active` - Active * `planned` - Planned * `staged` - Staged * `failed` - Failed * `inventory` - Inventory * `decommissioning` - Decommissioning
type BulkDeviceWithConfigContextRequestStatus string

// List of BulkDeviceWithConfigContextRequest_status
const (
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_OFFLINE         BulkDeviceWithConfigContextRequestStatus = "offline"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_ACTIVE          BulkDeviceWithConfigContextRequestStatus = "active"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_PLANNED         BulkDeviceWithConfigContextRequestStatus = "planned"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_STAGED          BulkDeviceWithConfigContextRequestStatus = "staged"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_FAILED          BulkDeviceWithConfigContextRequestStatus = "failed"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_INVENTORY       BulkDeviceWithConfigContextRequestStatus = "inventory"
	BULKDEVICEWITHCONFIGCONTEXTREQUESTSTATUS_DECOMMISSIONING BulkDeviceWithConfigContextRequestStatus = "decommissioning"
)

// All allowed values of BulkDeviceWithConfigContextRequestStatus enum
var AllowedBulkDeviceWithConfigContextRequestStatusEnumValues = []BulkDeviceWithConfigContextRequestStatus{
	"offline",
	"active",
	"planned",
	"staged",
	"failed",
	"inventory",
	"decommissioning",
}

func (v *BulkDeviceWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkDeviceWithConfigContextRequestStatus(value)
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkDeviceWithConfigContextRequestStatus", value)
}

// NewBulkDeviceWithConfigContextRequestStatusFromValue returns a pointer to a valid BulkDeviceWithConfigContextRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkDeviceWithConfigContextRequestStatusFromValue(v string) (*BulkDeviceWithConfigContextRequestStatus, error) {
	ev := BulkDeviceWithConfigContextRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkDeviceWithConfigContextRequestStatus: valid values are %v", v, AllowedBulkDeviceWithConfigContextRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkDeviceWithConfigContextRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkDeviceWithConfigContextRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkDeviceWithConfigContextRequest_status value
func (v BulkDeviceWithConfigContextRequestStatus) Ptr() *BulkDeviceWithConfigContextRequestStatus {
	return &v
}

type NullableBulkDeviceWithConfigContextRequestStatus struct {
	value *BulkDeviceWithConfigContextRequestStatus
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestStatus) Get() *BulkDeviceWithConfigContextRequestStatus {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestStatus) Set(val *BulkDeviceWithConfigContextRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestStatus(val *BulkDeviceWithConfigContextRequestStatus) *NullableBulkDeviceWithConfigContextRequestStatus {
	return &NullableBulkDeviceWithConfigContextRequestStatus{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
