/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the ScriptDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptDetail{}

// ScriptDetail Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
type ScriptDetail struct {
	Id                   int32          `json:"id"`
	Url                  string         `json:"url"`
	DisplayUrl           *string        `json:"display_url,omitempty"`
	Module               int32          `json:"module"`
	Name                 string         `json:"name"`
	Description          NullableString `json:"description,omitempty"`
	Vars                 interface{}    `json:"vars,omitempty"`
	Result               Job            `json:"result"`
	Display              string         `json:"display"`
	IsExecutable         bool           `json:"is_executable"`
	AdditionalProperties map[string]interface{}
}

type _ScriptDetail ScriptDetail

// NewScriptDetail instantiates a new ScriptDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptDetail(id int32, url string, module int32, name string, result Job, display string, isExecutable bool) *ScriptDetail {
	this := ScriptDetail{}
	this.Id = id
	this.Url = url
	this.Module = module
	this.Name = name
	this.Result = result
	this.Display = display
	this.IsExecutable = isExecutable
	return &this
}

// NewScriptDetailWithDefaults instantiates a new ScriptDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptDetailWithDefaults() *ScriptDetail {
	this := ScriptDetail{}
	return &this
}

// GetId returns the Id field value
func (o *ScriptDetail) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ScriptDetail) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *ScriptDetail) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ScriptDetail) SetUrl(v string) {
	o.Url = v
}

// GetDisplayUrl returns the DisplayUrl field value if set, zero value otherwise.
func (o *ScriptDetail) GetDisplayUrl() string {
	if o == nil || IsNil(o.DisplayUrl) {
		var ret string
		return ret
	}
	return *o.DisplayUrl
}

// GetDisplayUrlOk returns a tuple with the DisplayUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetDisplayUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayUrl) {
		return nil, false
	}
	return o.DisplayUrl, true
}

// HasDisplayUrl returns a boolean if a field has been set.
func (o *ScriptDetail) HasDisplayUrl() bool {
	if o != nil && !IsNil(o.DisplayUrl) {
		return true
	}

	return false
}

// SetDisplayUrl gets a reference to the given string and assigns it to the DisplayUrl field.
func (o *ScriptDetail) SetDisplayUrl(v string) {
	o.DisplayUrl = &v
}

// GetModule returns the Module field value
func (o *ScriptDetail) GetModule() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Module
}

// GetModuleOk returns a tuple with the Module field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetModuleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Module, true
}

// SetModule sets field value
func (o *ScriptDetail) SetModule(v int32) {
	o.Module = v
}

// GetName returns the Name field value
func (o *ScriptDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScriptDetail) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScriptDetail) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScriptDetail) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ScriptDetail) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ScriptDetail) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ScriptDetail) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ScriptDetail) UnsetDescription() {
	o.Description.Unset()
}

// GetVars returns the Vars field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScriptDetail) GetVars() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Vars
}

// GetVarsOk returns a tuple with the Vars field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScriptDetail) GetVarsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Vars) {
		return nil, false
	}
	return &o.Vars, true
}

// HasVars returns a boolean if a field has been set.
func (o *ScriptDetail) HasVars() bool {
	if o != nil && !IsNil(o.Vars) {
		return true
	}

	return false
}

// SetVars gets a reference to the given interface{} and assigns it to the Vars field.
func (o *ScriptDetail) SetVars(v interface{}) {
	o.Vars = v
}

// GetResult returns the Result field value
func (o *ScriptDetail) GetResult() Job {
	if o == nil {
		var ret Job
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetResultOk() (*Job, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ScriptDetail) SetResult(v Job) {
	o.Result = v
}

// GetDisplay returns the Display field value
func (o *ScriptDetail) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *ScriptDetail) SetDisplay(v string) {
	o.Display = v
}

// GetIsExecutable returns the IsExecutable field value
func (o *ScriptDetail) GetIsExecutable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsExecutable
}

// GetIsExecutableOk returns a tuple with the IsExecutable field value
// and a boolean to check if the value has been set.
func (o *ScriptDetail) GetIsExecutableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsExecutable, true
}

// SetIsExecutable sets field value
func (o *ScriptDetail) SetIsExecutable(v bool) {
	o.IsExecutable = v
}

func (o ScriptDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	if !IsNil(o.DisplayUrl) {
		toSerialize["display_url"] = o.DisplayUrl
	}
	toSerialize["module"] = o.Module
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Vars != nil {
		toSerialize["vars"] = o.Vars
	}
	toSerialize["result"] = o.Result
	toSerialize["display"] = o.Display
	toSerialize["is_executable"] = o.IsExecutable

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScriptDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"module",
		"name",
		"result",
		"display",
		"is_executable",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScriptDetail := _ScriptDetail{}

	err = json.Unmarshal(data, &varScriptDetail)

	if err != nil {
		return err
	}

	*o = ScriptDetail(varScriptDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display_url")
		delete(additionalProperties, "module")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "vars")
		delete(additionalProperties, "result")
		delete(additionalProperties, "display")
		delete(additionalProperties, "is_executable")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScriptDetail struct {
	value *ScriptDetail
	isSet bool
}

func (v NullableScriptDetail) Get() *ScriptDetail {
	return v.value
}

func (v *NullableScriptDetail) Set(val *ScriptDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptDetail(val *ScriptDetail) *NullableScriptDetail {
	return &NullableScriptDetail{value: val, isSet: true}
}

func (v NullableScriptDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
