/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceWithConfigContextRequestVirtualChassis - struct for BulkDeviceWithConfigContextRequestVirtualChassis
type BulkDeviceWithConfigContextRequestVirtualChassis struct {
	BriefVirtualChassisRequest *BriefVirtualChassisRequest
	Int32                      *int32
}

// BriefVirtualChassisRequestAsBulkDeviceWithConfigContextRequestVirtualChassis is a convenience function that returns BriefVirtualChassisRequest wrapped in BulkDeviceWithConfigContextRequestVirtualChassis
func BriefVirtualChassisRequestAsBulkDeviceWithConfigContextRequestVirtualChassis(v *BriefVirtualChassisRequest) BulkDeviceWithConfigContextRequestVirtualChassis {
	return BulkDeviceWithConfigContextRequestVirtualChassis{
		BriefVirtualChassisRequest: v,
	}
}

// int32AsBulkDeviceWithConfigContextRequestVirtualChassis is a convenience function that returns int32 wrapped in BulkDeviceWithConfigContextRequestVirtualChassis
func Int32AsBulkDeviceWithConfigContextRequestVirtualChassis(v *int32) BulkDeviceWithConfigContextRequestVirtualChassis {
	return BulkDeviceWithConfigContextRequestVirtualChassis{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceWithConfigContextRequestVirtualChassis) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefVirtualChassisRequest
	err = newStrictDecoder(data).Decode(&dst.BriefVirtualChassisRequest)
	if err == nil {
		jsonBriefVirtualChassisRequest, _ := json.Marshal(dst.BriefVirtualChassisRequest)
		if string(jsonBriefVirtualChassisRequest) == "{}" { // empty struct
			dst.BriefVirtualChassisRequest = nil
		} else {
			if err = validator.Validate(dst.BriefVirtualChassisRequest); err != nil {
				dst.BriefVirtualChassisRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefVirtualChassisRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefVirtualChassisRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceWithConfigContextRequestVirtualChassis)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestVirtualChassis): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestVirtualChassis)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestVirtualChassis): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceWithConfigContextRequestVirtualChassis)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceWithConfigContextRequestVirtualChassis) MarshalJSON() ([]byte, error) {
	if src.BriefVirtualChassisRequest != nil {
		return json.Marshal(&src.BriefVirtualChassisRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceWithConfigContextRequestVirtualChassis) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefVirtualChassisRequest != nil {
		return obj.BriefVirtualChassisRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceWithConfigContextRequestVirtualChassis) GetActualInstanceValue() interface{} {
	if obj.BriefVirtualChassisRequest != nil {
		return *obj.BriefVirtualChassisRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceWithConfigContextRequestVirtualChassis struct {
	value *BulkDeviceWithConfigContextRequestVirtualChassis
	isSet bool
}

func (v NullableBulkDeviceWithConfigContextRequestVirtualChassis) Get() *BulkDeviceWithConfigContextRequestVirtualChassis {
	return v.value
}

func (v *NullableBulkDeviceWithConfigContextRequestVirtualChassis) Set(val *BulkDeviceWithConfigContextRequestVirtualChassis) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceWithConfigContextRequestVirtualChassis) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceWithConfigContextRequestVirtualChassis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceWithConfigContextRequestVirtualChassis(val *BulkDeviceWithConfigContextRequestVirtualChassis) *NullableBulkDeviceWithConfigContextRequestVirtualChassis {
	return &NullableBulkDeviceWithConfigContextRequestVirtualChassis{value: val, isSet: true}
}

func (v NullableBulkDeviceWithConfigContextRequestVirtualChassis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceWithConfigContextRequestVirtualChassis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
