/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkPowerFeedRequestStatus * `offline` - Offline * `active` - Active * `planned` - Planned * `failed` - Failed
type BulkPowerFeedRequestStatus string

// List of BulkPowerFeedRequest_status
const (
	BULKPOWERFEEDREQUESTSTATUS_OFFLINE BulkPowerFeedRequestStatus = "offline"
	BULKPOWERFEEDREQUESTSTATUS_ACTIVE  BulkPowerFeedRequestStatus = "active"
	BULKPOWERFEEDREQUESTSTATUS_PLANNED BulkPowerFeedRequestStatus = "planned"
	BULKPOWERFEEDREQUESTSTATUS_FAILED  BulkPowerFeedRequestStatus = "failed"
)

// All allowed values of BulkPowerFeedRequestStatus enum
var AllowedBulkPowerFeedRequestStatusEnumValues = []BulkPowerFeedRequestStatus{
	"offline",
	"active",
	"planned",
	"failed",
}

func (v *BulkPowerFeedRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkPowerFeedRequestStatus(value)
	for _, existing := range AllowedBulkPowerFeedRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkPowerFeedRequestStatus", value)
}

// NewBulkPowerFeedRequestStatusFromValue returns a pointer to a valid BulkPowerFeedRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkPowerFeedRequestStatusFromValue(v string) (*BulkPowerFeedRequestStatus, error) {
	ev := BulkPowerFeedRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkPowerFeedRequestStatus: valid values are %v", v, AllowedBulkPowerFeedRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkPowerFeedRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkPowerFeedRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkPowerFeedRequest_status value
func (v BulkPowerFeedRequestStatus) Ptr() *BulkPowerFeedRequestStatus {
	return &v
}

type NullableBulkPowerFeedRequestStatus struct {
	value *BulkPowerFeedRequestStatus
	isSet bool
}

func (v NullableBulkPowerFeedRequestStatus) Get() *BulkPowerFeedRequestStatus {
	return v.value
}

func (v *NullableBulkPowerFeedRequestStatus) Set(val *BulkPowerFeedRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkPowerFeedRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkPowerFeedRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkPowerFeedRequestStatus(val *BulkPowerFeedRequestStatus) *NullableBulkPowerFeedRequestStatus {
	return &NullableBulkPowerFeedRequestStatus{value: val, isSet: true}
}

func (v NullableBulkPowerFeedRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkPowerFeedRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
