/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkDeviceTypeRequestDefaultPlatform - struct for BulkDeviceTypeRequestDefaultPlatform
type BulkDeviceTypeRequestDefaultPlatform struct {
	BriefPlatformRequest *BriefPlatformRequest
	Int32                *int32
}

// BriefPlatformRequestAsBulkDeviceTypeRequestDefaultPlatform is a convenience function that returns BriefPlatformRequest wrapped in BulkDeviceTypeRequestDefaultPlatform
func BriefPlatformRequestAsBulkDeviceTypeRequestDefaultPlatform(v *BriefPlatformRequest) BulkDeviceTypeRequestDefaultPlatform {
	return BulkDeviceTypeRequestDefaultPlatform{
		BriefPlatformRequest: v,
	}
}

// int32AsBulkDeviceTypeRequestDefaultPlatform is a convenience function that returns int32 wrapped in BulkDeviceTypeRequestDefaultPlatform
func Int32AsBulkDeviceTypeRequestDefaultPlatform(v *int32) BulkDeviceTypeRequestDefaultPlatform {
	return BulkDeviceTypeRequestDefaultPlatform{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkDeviceTypeRequestDefaultPlatform) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefPlatformRequest
	err = newStrictDecoder(data).Decode(&dst.BriefPlatformRequest)
	if err == nil {
		jsonBriefPlatformRequest, _ := json.Marshal(dst.BriefPlatformRequest)
		if string(jsonBriefPlatformRequest) == "{}" { // empty struct
			dst.BriefPlatformRequest = nil
		} else {
			if err = validator.Validate(dst.BriefPlatformRequest); err != nil {
				dst.BriefPlatformRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefPlatformRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefPlatformRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkDeviceTypeRequestDefaultPlatform)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceTypeRequestDefaultPlatform): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceTypeRequestDefaultPlatform)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceTypeRequestDefaultPlatform): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkDeviceTypeRequestDefaultPlatform)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkDeviceTypeRequestDefaultPlatform) MarshalJSON() ([]byte, error) {
	if src.BriefPlatformRequest != nil {
		return json.Marshal(&src.BriefPlatformRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkDeviceTypeRequestDefaultPlatform) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefPlatformRequest != nil {
		return obj.BriefPlatformRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkDeviceTypeRequestDefaultPlatform) GetActualInstanceValue() interface{} {
	if obj.BriefPlatformRequest != nil {
		return *obj.BriefPlatformRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkDeviceTypeRequestDefaultPlatform struct {
	value *BulkDeviceTypeRequestDefaultPlatform
	isSet bool
}

func (v NullableBulkDeviceTypeRequestDefaultPlatform) Get() *BulkDeviceTypeRequestDefaultPlatform {
	return v.value
}

func (v *NullableBulkDeviceTypeRequestDefaultPlatform) Set(val *BulkDeviceTypeRequestDefaultPlatform) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeviceTypeRequestDefaultPlatform) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeviceTypeRequestDefaultPlatform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeviceTypeRequestDefaultPlatform(val *BulkDeviceTypeRequestDefaultPlatform) *NullableBulkDeviceTypeRequestDefaultPlatform {
	return &NullableBulkDeviceTypeRequestDefaultPlatform{value: val, isSet: true}
}

func (v NullableBulkDeviceTypeRequestDefaultPlatform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeviceTypeRequestDefaultPlatform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
