/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkVirtualMachineWithConfigContextRequestVirtualMachineType - struct for BulkVirtualMachineWithConfigContextRequestVirtualMachineType
type BulkVirtualMachineWithConfigContextRequestVirtualMachineType struct {
	BriefVirtualMachineTypeRequest *BriefVirtualMachineTypeRequest
	Int32                          *int32
}

// BriefVirtualMachineTypeRequestAsBulkVirtualMachineWithConfigContextRequestVirtualMachineType is a convenience function that returns BriefVirtualMachineTypeRequest wrapped in BulkVirtualMachineWithConfigContextRequestVirtualMachineType
func BriefVirtualMachineTypeRequestAsBulkVirtualMachineWithConfigContextRequestVirtualMachineType(v *BriefVirtualMachineTypeRequest) BulkVirtualMachineWithConfigContextRequestVirtualMachineType {
	return BulkVirtualMachineWithConfigContextRequestVirtualMachineType{
		BriefVirtualMachineTypeRequest: v,
	}
}

// int32AsBulkVirtualMachineWithConfigContextRequestVirtualMachineType is a convenience function that returns int32 wrapped in BulkVirtualMachineWithConfigContextRequestVirtualMachineType
func Int32AsBulkVirtualMachineWithConfigContextRequestVirtualMachineType(v *int32) BulkVirtualMachineWithConfigContextRequestVirtualMachineType {
	return BulkVirtualMachineWithConfigContextRequestVirtualMachineType{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkVirtualMachineWithConfigContextRequestVirtualMachineType) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefVirtualMachineTypeRequest
	err = newStrictDecoder(data).Decode(&dst.BriefVirtualMachineTypeRequest)
	if err == nil {
		jsonBriefVirtualMachineTypeRequest, _ := json.Marshal(dst.BriefVirtualMachineTypeRequest)
		if string(jsonBriefVirtualMachineTypeRequest) == "{}" { // empty struct
			dst.BriefVirtualMachineTypeRequest = nil
		} else {
			if err = validator.Validate(dst.BriefVirtualMachineTypeRequest); err != nil {
				dst.BriefVirtualMachineTypeRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefVirtualMachineTypeRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefVirtualMachineTypeRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkVirtualMachineWithConfigContextRequestVirtualMachineType)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestVirtualMachineType): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestVirtualMachineType)")
		}
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestVirtualMachineType): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVirtualMachineWithConfigContextRequestVirtualMachineType)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkVirtualMachineWithConfigContextRequestVirtualMachineType) MarshalJSON() ([]byte, error) {
	if src.BriefVirtualMachineTypeRequest != nil {
		return json.Marshal(&src.BriefVirtualMachineTypeRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkVirtualMachineWithConfigContextRequestVirtualMachineType) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefVirtualMachineTypeRequest != nil {
		return obj.BriefVirtualMachineTypeRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkVirtualMachineWithConfigContextRequestVirtualMachineType) GetActualInstanceValue() interface{} {
	if obj.BriefVirtualMachineTypeRequest != nil {
		return *obj.BriefVirtualMachineTypeRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType struct {
	value *BulkVirtualMachineWithConfigContextRequestVirtualMachineType
	isSet bool
}

func (v NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) Get() *BulkVirtualMachineWithConfigContextRequestVirtualMachineType {
	return v.value
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) Set(val *BulkVirtualMachineWithConfigContextRequestVirtualMachineType) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType(val *BulkVirtualMachineWithConfigContextRequestVirtualMachineType) *NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType {
	return &NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType{value: val, isSet: true}
}

func (v NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestVirtualMachineType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
