/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkCableRequestColor - struct for BulkCableRequestColor
type BulkCableRequestColor struct {
	String *string
}

// stringAsBulkCableRequestColor is a convenience function that returns string wrapped in BulkCableRequestColor
func StringAsBulkCableRequestColor(v *string) BulkCableRequestColor {
	return BulkCableRequestColor{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkCableRequestColor) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkCableRequestColor)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkCableRequestColor): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkCableRequestColor)")
		}
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkCableRequestColor) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkCableRequestColor) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkCableRequestColor) GetActualInstanceValue() interface{} {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableBulkCableRequestColor struct {
	value *BulkCableRequestColor
	isSet bool
}

func (v NullableBulkCableRequestColor) Get() *BulkCableRequestColor {
	return v.value
}

func (v *NullableBulkCableRequestColor) Set(val *BulkCableRequestColor) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCableRequestColor) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCableRequestColor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCableRequestColor(val *BulkCableRequestColor) *NullableBulkCableRequestColor {
	return &NullableBulkCableRequestColor{value: val, isSet: true}
}

func (v NullableBulkCableRequestColor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCableRequestColor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
