/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.6.8-Docker-5.0.2 (4.6)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkVirtualMachineWithConfigContextRequestStartOnBoot * `on` - On * `off` - Off * `laststate` - Last State
type BulkVirtualMachineWithConfigContextRequestStartOnBoot string

// List of BulkVirtualMachineWithConfigContextRequest_start_on_boot
const (
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTARTONBOOT_ON        BulkVirtualMachineWithConfigContextRequestStartOnBoot = "on"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTARTONBOOT_OFF       BulkVirtualMachineWithConfigContextRequestStartOnBoot = "off"
	BULKVIRTUALMACHINEWITHCONFIGCONTEXTREQUESTSTARTONBOOT_LASTSTATE BulkVirtualMachineWithConfigContextRequestStartOnBoot = "laststate"
)

// All allowed values of BulkVirtualMachineWithConfigContextRequestStartOnBoot enum
var AllowedBulkVirtualMachineWithConfigContextRequestStartOnBootEnumValues = []BulkVirtualMachineWithConfigContextRequestStartOnBoot{
	"on",
	"off",
	"laststate",
}

func (v *BulkVirtualMachineWithConfigContextRequestStartOnBoot) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkVirtualMachineWithConfigContextRequestStartOnBoot(value)
	for _, existing := range AllowedBulkVirtualMachineWithConfigContextRequestStartOnBootEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkVirtualMachineWithConfigContextRequestStartOnBoot", value)
}

// NewBulkVirtualMachineWithConfigContextRequestStartOnBootFromValue returns a pointer to a valid BulkVirtualMachineWithConfigContextRequestStartOnBoot
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkVirtualMachineWithConfigContextRequestStartOnBootFromValue(v string) (*BulkVirtualMachineWithConfigContextRequestStartOnBoot, error) {
	ev := BulkVirtualMachineWithConfigContextRequestStartOnBoot(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkVirtualMachineWithConfigContextRequestStartOnBoot: valid values are %v", v, AllowedBulkVirtualMachineWithConfigContextRequestStartOnBootEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkVirtualMachineWithConfigContextRequestStartOnBoot) IsValid() bool {
	for _, existing := range AllowedBulkVirtualMachineWithConfigContextRequestStartOnBootEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkVirtualMachineWithConfigContextRequest_start_on_boot value
func (v BulkVirtualMachineWithConfigContextRequestStartOnBoot) Ptr() *BulkVirtualMachineWithConfigContextRequestStartOnBoot {
	return &v
}

type NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot struct {
	value *BulkVirtualMachineWithConfigContextRequestStartOnBoot
	isSet bool
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) Get() *BulkVirtualMachineWithConfigContextRequestStartOnBoot {
	return v.value
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) Set(val *BulkVirtualMachineWithConfigContextRequestStartOnBoot) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVirtualMachineWithConfigContextRequestStartOnBoot(val *BulkVirtualMachineWithConfigContextRequestStartOnBoot) *NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot {
	return &NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot{value: val, isSet: true}
}

func (v NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVirtualMachineWithConfigContextRequestStartOnBoot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
